### ISSUE TITLE
EventChart zoom error

### ISSUE THREAD

**Issue by primozs** [esnet/react-timeseries-charts#100]
When you zoom in event chart so one or more events falls out of visible area react errors start to appear.

This is also visible on the demo chart:
1. open dev tools
2. on chat zoom in until event falls out of visible area
http://software.es.net/react-timeseries-charts/#/example/outages?_k=gnssm6

**Comment by pjm17971** [comment]
Thanks!

**Comment by pjm17971** [comment]
The EventCharts are pretty minimal, but gets a certain type of job done. Thanks for cleaning this up. What are you using it for, if I may ask?

**Comment by primozs** [comment]
@pjm17971 I am using it to display track events like engine on, airspace infringement. But I have also styling issues with them. I need them very slim in height and hover text label is not possible to style, xy position. For this I would open new pull request to set the label text xy offset. Like this the style would not break for the current users.

**Comment by pjm17971** [comment]
@primozs sounds good!
