### ISSUE TITLE
Grid lines style customization 

### ISSUE THREAD

**Issue by ontofractal** [esnet/react-timeseries-charts#105]
Is it possible to customize the grid (as in showGrid prop of the ChartContainer) to change the color, dashed line format, etc?

Thanks

**Comment by pjm17971** [comment]
Not directly, but they do have a CSS class on it ("tick") under a "x axis" classed group. So it should be possible to apply a CSS rule to those elements.

**Comment by ontofractal** [comment]
Got it, thanks!
