### ISSUE TITLE
TimeRangeMarker.js - Cannot read property 'func' of undefined

### ISSUE THREAD

**Issue by patryk0605** [esnet/react-timeseries-charts#107]
Receiving the following error in console after upgrading from **v0.10.2** to **v0.11.0**:

```
TimeRangeMarker.js:121 Uncaught TypeError: Cannot read property 'func' of undefined
(anonymous function) @ TimeRangeMarker.js:121
...
```

**Comment by pjm17971** [comment]
Sorry about that. I just pushed 0.11.1 that should fix it.

**Comment by patryk0605** [comment]
@pjm17971 no worries! All good now, appreciate the fast response.
