### ISSUE TITLE
Resizable didn't work after update

### ISSUE THREAD

**Issue by matolsen** [esnet/react-timeseries-charts#109]
When I update from "react-timeseries-charts": "^0.10.2" to "react-timeseries-charts": "^0.11.1" the Resizable component stopped working. 

```
<Resizable>
            <ChartContainer>....
            </ChartContainer>
</Resizable>

```
After I uninstalled and reinstalled 0.10.2 Resizable worked again.

**Comment by pjm17971** [comment]
Thanks for the report!

Was there any error? What exactly wasn't working?

We use the latest version with Resizable in multiple contexts and haven't seen any change of behavior, so any additional info would be helpful. What version of react are using?

**Comment by matolsen** [comment]
Sorry for not getting back to you sooner. No errors, the width just wasn't changing like it does in version 0.10.2 - I'll try to test it this week and see if I can get it working in a simpler project.

**Comment by matolsen** [comment]
I pulled down the code to run locally and notice the baseline example has a resizable component and it doesn't resize. http://software.es.net/react-timeseries-charts/#/example/baselines?_k=far5xm

![resize](https://cloud.githubusercontent.com/assets/7564489/21509115/0eea8adc-cc54-11e6-86d6-8be6542a6890.png)

**Comment by pjm17971** [comment]
What version of React are you using? 0.14.x or 15.x.x ? I'll try to reproduce when I'm back at work next week.

**Comment by matolsen** [comment]
react version 15.4.1

**Comment by pjm17971** [comment]
Thanks for reporting this.  Should be fixed now in v0.11.2.

**Comment by matolsen** [comment]
Awesome, works great!

**Comment by osipuk** [comment]
My react version is 16.3.2
react-timeseries-charts version is ^0.14.0.
My code is 
<Resizable>
            <ChartContainer>....
            </ChartContainer>
</Resizable>
The chart is not appeared.
Please help me
