### ISSUE TITLE
Resizable Throwing Console Error - Cannot read property 'offsetWidth' of null

### ISSUE THREAD

**Issue by matolsen** [esnet/react-timeseries-charts#110]
Uncaught TypeError: Cannot read property 'offsetWidth' of null
    at t.value (Resizable.js:36)
    at Resizable.js:26

I first saw this in my code and it's also happening on the demo. 

![resizable-error](https://cloud.githubusercontent.com/assets/7564489/21613138/f444b1c8-d1a1-11e6-80a6-86276a50ca72.png)

**Comment by matolsen** [comment]
I fixed this in my project by updating the Resizeable.js. I added an if around the setState so setState doesn't get set if the container is null
 
`    key: 'handleResize',
    value: function handleResize() {
      if(this.container) {
        this.setState({
          width: this.container.offsetWidth
        });
      }
    }`

**Comment by pjm17971** [comment]
Thanks for the follow up. Yeah, this change is actually in my branch too. I'm not really sure why that's needed, because in theory render() should be called first and so this.container should be defined. Anyway, I'm glad we agree on a resolution to this.

**Comment by pjm17971** [comment]
This change is now in the release. @matolsen I take it this is fixed for you now?
