### ISSUE TITLE
Lines not appearing on chart

### ISSUE THREAD

**Issue by mikesparr** [esnet/react-timeseries-charts#113]
This has to be something I'm doing but I have a few sample points plotted based on your examples, but changed timestamps. I created range based on begin/end and chart renders fine but no lines or plotted points. 

 * React: `15.4.2`
 * Charts lib: `^0.11.2`
 * pondjs: `^0.7.2`

~~~
import React, { Component } from 'react'
import { TimeSeries, TimeRange } from "pondjs"
import { Charts, ChartContainer, ChartRow, YAxis, LineChart } from 'react-timeseries-charts'

const data = {
    name: "leads",
    columns: ["time", "count"],
    points: [
        [1484121499495, 2],
        [1484131499495, 9],
        [1484141999495, 14],
        [1484152499495, 27]
    ]
}
const timeseries = new TimeSeries(data)
const style = {
    value: {
        stroke: "#a02c2c",
        opacity: 0.2
    }
}

// ...

<ChartContainer timeRange={new TimeRange(1484121499495, 1484152499495)} width={800}>
    <ChartRow height="150">
        <YAxis id="axis1" label="TOT" min={0} max={50} width="60" type="linear" format=","/>
        <Charts>
            <LineChart axis="axis1" series={timeseries} style={style}/>
        </Charts>
    </ChartRow>
</ChartContainer>
~~~

Displays like this but no data appearing? Do I have too few points or something else wrong. Thanks so much!

<img width="774" alt="screen shot 2017-01-15 at 10 55 04 pm" src="https://cloud.githubusercontent.com/assets/5553105/21972287/b616b99a-db75-11e6-9e20-b84107c2ccd7.png">

**Comment by mikesparr** [comment]
I found issue:

 * I need to declare `columns={["count"]}` in `LineChart` changing to:
~~~
<LineChart axis="axis1" series={timeseries} columns={["count"]} style={style}/>
~~~

 * I need to change style to:
~~~
const style = {
    count: {
        stroke: "#a02c2c",
        opacity: 0.2
    }
}
~~~

It now appears like this. It wasn't clear the relationship between style object key name and requirement of columns prop so hope this helps someone else.

<img width="746" alt="screen shot 2017-01-15 at 11 25 08 pm" src="https://cloud.githubusercontent.com/assets/5553105/21972880/e4925302-db79-11e6-918a-a1bb94227b81.png">

**Comment by pjm17971** [comment]
Cool, thanks for checking back in about this. I'll try to make some docs tweaks to make that cleared.

**Comment by foxish** [comment]
Hit the same snag. Thank you for posting what worked - also, it seems like https://github.com/esnet/react-timeseries-charts#getting-started should have the examples with `columns=...` on the LineChart? Is there a way for it to work without that at all?

Happy to make a PR if that's appropriate.
