### ISSUE TITLE
Ability to toggle a row

### ISSUE THREAD

**Issue by pjm17971** [esnet/react-timeseries-charts#116]
Ideally you'd just set canToggle=true on the row and it would handle the rest. The result would be a toggle triangle at the end or beginning of the row. Currently sizing is based on axis widths and total width, so that calculation would need to take that into account. Bonus points: toggleColor to color the toggle (likely to match the chart shown in it) and toggleTitle for extra information when the row is collapsed.

cc: @apertome

**Comment by sartaj10** [comment]
Added in #208
