### ISSUE TITLE
BarChart error in render bars about `event.index` not a function

### ISSUE THREAD

**Issue by mikesparr** [esnet/react-timeseries-charts#117]
Latest version from `npm` of this lib and react/react-scripts.

I have `LineChart` working fine in one page and copied your example for `BarChart` for another page but cannot seem to get it to render. After stepping through each issue I'm stuck on this one and I have valid `TimeSeries` and `TimeRange` objects with data and it's not clear why nothing displays.

Expect to see bar charts with 7 days of bars

<img width="508" alt="screen shot 2017-01-29 at 6 30 56 pm" src="https://cloud.githubusercontent.com/assets/5553105/22410164/99b945c4-e651-11e6-83a0-02711783422d.png">

## Relevant code with test data
~~~
const data = {
  name: "opportunities",
  columns: [
    "time",
    "value"
  ],
  points: [
    [1483919916773,1],
    [1484438316773,1],
    [1484870316773,2],
    [1485215916773,0],
    [1485475116773,1],
    [1485647916773,5],
    [1485734231283,2]
  ]
}

const series = new TimeSeries(data)

const startDate = moment.utc().subtract(1, 'week')
const endDate = moment.utc()
const timeRange = new TimeRange(parseInt(startDate.format('x'), 10), parseInt(endDate.format('x'), 10))

const style = {
  value: {
    normal: {fill: "#A5C8E1"},
    highlighted: {fill: "#bfdff6"},
    selected: {fill: "#5aa2d5"},
    muted: {fill: "#A5C8E1", opacity: 0.4}
  }
}

// render

    const max = 10
    const maxTimeDate = new Date(moment.utc().add(1, 'day').format("MMM DD, YYYY HH:MM"))
    const minTimeDate = new Date(moment.utc().subtract(1, 'year').format("MMM DD, YYYY HH:MM"))
    const minDurationSeconds = 600

            <ChartContainer
              width={600}
              utc={false}
              timeRange={timeRange}
              format="day"
              enablePanZoom={true} onTimeRangeChanged={this.handleTimeRangeChange}
              maxTime={maxTimeDate}
              minTime={minTimeDate}
              minDuration={minDurationSeconds * 1000}>
              <ChartRow height="150">
                <YAxis
                  id="tot"
                  label="TOT"
                  min={0} max={max}
                  width="60" />
                <Charts>
                  <BarChart
                    axis="tot"
                    style={style}
                    columns={["value"]}
                    series={series}
                    highlight={this.state.highlight}
                    onHighlightChange={highlight => this.setState({highlight})}
                    selection={this.state.selection}
                    onSelectionChange={selection => this.setState({selection})} />
                </Charts>
              </ChartRow>
            </ChartContainer>
~~~

**Comment by pjm17971** [comment]
I think the column should be index:
```
  columns: [
    "time",
    "value"
  ]
```
Should be:
```
  columns: [
    "time",
    "index"
  ]
```
And the first item of the points should be a string Index. e.g. "2016-09-17" or "1d-1234"
http://software.es.net/pond/#/index

**Comment by regoaruorg** [comment]
Also just started using the bar chart, figured out the problem described in the initial issue without too  much hassle...but i have an another problem.

Is it possible to format the "Index" string for info labels? As i understand, if i want to use seconds, hours etc. i need to use the second format you described (1h-.....)? But when using this format, the same index string is used in the bar chart info labels and that can be confusing for the end user. Did not find any way to format this correctly from the docs.

![time](https://cloud.githubusercontent.com/assets/13510570/22416821/753735d4-e6d9-11e6-9d3a-9ddadf10f6f2.png)

**Comment by mikesparr** [comment]
Thanks @pjm17971 that seemed to do the trick. It's odd indeed that the `index` needs to be string, but then also in date format matching time series. 

What would be nice is if in your docs examples you had everything for a working example, even if like above a small snippet of hard-coded values just to show how to render the charts.  Then, the live demos with larger data set as you have now as well.

**Comment by pjm17971** [comment]
Yeah, it's a common problem. I'll give it some thought about how to build that up. Thanks for the feedback.

For the above issue with the date format, I can probably add something to get that working. It seems like the infoTimeFormat prop is not passed on in the case of IndexedEvents such as the barchart, it just asks it for its string representation (which is the ugly thing you see). I'm thinking I'd let infoTimeFormat be a function and I'll pass in the Index and you can return a string. Give me a day or two.

**Comment by pjm17971** [comment]
I've added a new item for better docs for BarCharts. And the formatting issue also described here was added. So I'm closing this.
