### ISSUE TITLE
Failed prop type: Invalid prop `trackerInfoValues` supplied to `ChartRow`.

### ISSUE THREAD

**Issue by loganbfisher** [esnet/react-timeseries-charts#123]
I keep getting this error when following the documentation for ChartRow.
`Failed prop type: Invalid prop 'trackerInfoValues' supplied to 'ChartRow'.`

```
<ChartContainer
                timeRange={lotOneSeries.range()}
                trackerPosition={this.state.tracker}
                onTrackerChanged={this.handleTrackerChanged}
                enablePanZoom={true}
                minDuration={1000}
                onBackgroundClick={() => self.setState({selection: null})}
                onTimeRangeChanged={this.handleTimeRangeChange}>
<ChartRow
     height="240"
     trackerInfoValues={[{label: "Speed", value: 45}]}
     trackerInfoHeight={50}
     trackerInfoWidth={100}>
```

**Comment by pjm17971** [comment]
I think the 45 should be a string

**Comment by loganbfisher** [comment]
@pjm17971 I changed it to a string and the error goes away but I don't see a info box showing up next to the tracker.

**Comment by pjm17971** [comment]
I'll try to take a look today. What kind of chart are you drawing? I don't think it matters, but I'll try to reproduce your setup and see if something is broken.
