### ISSUE TITLE
BoxChart not re-rendering bars on TimeSeries change, missing a getSeries()

### ISSUE THREAD

**Issue by yrokhlin** [esnet/react-timeseries-charts#126]
I'm updating my TimeSeries object by creating a new one, and it is definitely triggering the 
`seriesChanged` bool in the `shouldComponentUpdate` part of the `BoxChart` lifecycle. 

I noticed that `this.series` is only ever set in the `constructor` or on aggregation change.

I added a check to the `shouldComponentUpdate` lifecycle that triggers the `getSeries()` function, and it all started behaving as expected.

```
BoxChart

shouldComponentUpdate(nextProps) {

    .....

    let seriesChanged = false;
    if (oldSeries.length !== newSeries.length) {
      seriesChanged = true;
    } else {
      seriesChanged = !TimeSeries.is(oldSeries, newSeries);
    }

    // Added this to make it work
    if (seriesChanged) {
      this.series = getSeries(nextProps.series, nextProps.column);        
    }
}
```

**Comment by pjm17971** [comment]
Awesome! Thanks for catching this.

**Comment by yrokhlin** [comment]
Should I pull request this, or will it be making it in to version 0.12?

**Comment by pjm17971** [comment]
It should make it into 0.12. Thanks for pinging me, I think I didn't add this one to my notes, but I did add this fix.

**Comment by yrokhlin** [comment]
Just pulled in the latest 12.1, this issue seems to be persisting.

**Comment by pjm17971** [comment]
Sigh, yeah, I think I didn't merge it in. I'll fix it and push it into a patch in a sec.

**Comment by yrokhlin** [comment]
There's still a teeny tiny error in the code, you're passing stale props to `getSeries()`

`this.series = getSeries(this.props.series, this.props.column);`

should be

`this.series = getSeries(nextProps.series, nextProps.column);`

```    if (seriesChanged) {
      if (
        this.props.series._collection._type === TimeEvent // eslint-disable-line
      ) {
        this.series = getAggregatedSeries(
          this.props.series,
          this.props.column,
          this.props.aggregation
        );
      } else {
        this.series = getSeries(this.props.series, this.props.column); // Stale props, needs to be nextProps
      }
    }``

**Comment by pjm17971** [comment]
If I put that change up in a branch, can you test it for me?

**Comment by yrokhlin** [comment]
Sure, but for sure it's the stale props.

**Comment by pjm17971** [comment]
https://github.com/esnet/react-timeseries-charts/pull/131
