### ISSUE TITLE
TimeAxis format changes are not immediately rendered

### ISSUE THREAD

**Issue by paullexen** [esnet/react-timeseries-charts#128]
Because of the way the `TimeAxis` component is rendered, changing the `format` property doesn't immediately affect the rendered chart. The `renderTimeAxis` function uses `this.props`, but `renderTimeAxis` is called from within `componentWillReceiveProps`, so `this.props` doesn't have updated properties, so `renderTimeAxis` ends up using stale properties. 

To fix this, I changed the `componentWillReceiveProps` function to pass the `format` property on to the `renderTimeAxis` function. There are a couple other simple areas that are affected. Let me know if you want a pull request. 

 ```
 componentWillReceiveProps(nextProps) {
    const { scale, utc, format } = nextProps;
    if (scaleAsString(this.props.scale) !== scaleAsString(scale) ||
      this.props.utc !== utc) {
      this.renderTimeAxis(scale, format);
    }
  }
```

**Comment by pjm17971** [comment]
Makes sense. I've added this change and added it to the next release. Thanks for this!
