### ISSUE TITLE
Error in parsing usd_vs_aud.json and usd_vs_euro.json

### ISSUE THREAD

**Issue by mraak** [esnet/react-timeseries-charts#132]
In this example repo it works fine, but when I copy paste the files into anther project I get the following error.

Looks like there's nothing wrong with your example, but rather with my setup. Do you know what might it be?

[This is the file](https://github.com/esnet/react-timeseries-charts/blob/master/src/website/examples/currency/usd_vs_aud.json). And it seems that it doesn't like the 5th character which is the second double quote.

```json
ERROR in ./modules/usd_vs_euro.json
Module parse failed: E:\dev\projects\nodeprojects\react-router-tutorial\lessons\
08-index-routes\modules\usd_vs_euro.json Unexpected token (1:5)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:5)
    
```

**Comment by pjm17971** [comment]
Yeah, the examples are basically a create-react-app application, so in the background there's a webpack loader managing this. Probably json-loader. You can set that up yourself, or if you just want to work around that, you can add that into its own JS file and export it. In a general case you'd be loading data from a server, not off of a local json file.
