### ISSUE TITLE
Provide link to example source code from website

### ISSUE THREAD

**Issue by dmr** [esnet/react-timeseries-charts#133]
I really like this project so I browsed the examples on the website and I was missing one thing:
A link to the sourcecode.

I.e. http://software.es.net/react-timeseries-charts/#/example/stockchart
could provide a link to
https://github.com/esnet/react-timeseries-charts/blob/master/src/website/examples/stockchart/Index.js

Feel free to ignore this "issue" because really it's a great project but maybe I'm not the only one who has this thought.

**Comment by pjm17971** [comment]
Sounds like a good idea :)

**Comment by dmr** [comment]
Thank you for picking this up :)
