### ISSUE TITLE
Zoom to change YAxis range?

### ISSUE THREAD

**Issue by JulesAU** [esnet/react-timeseries-charts#134]
I note that `min` and `max` are hardcoded as YAxis props. For some kinds of time series data that don't exhibit mean reversion (i.e very different values over different time periods) it'd be nice to "zoom" the y-axis to view more detail in a narrower range.

This is particularly useful where multiple series are plotted; e.g. **open-low-high-close** stock or currency values.

Forgive me if this is already implemented; but I haven't been able to see how to do it.

Otherwise; I guess we need to hook into `onTimeRangeChanged`, calculate the min & max values for that time range, then set `YAxis.min` & `YAxis.max` accordingly.

Anyway - absolutely brilliant work on this library, and fantastic documentation, too! Thanks!

**Comment by pjm17971** [comment]
Thanks.

So, yes, we typically auto scale based on the time range and when re-rendering we change the `YAxis` `max` and `min` props. There's I think some examples of this on the website and is pretty easy with the (Pond) TimeSeries object you already are rendering to crop it to the range and ask it for the max and min.

Just so I understand though, you are talking about letting the user manually control this on the axis themselves? Did you have a particular interaction in mind? I've wondered about this is the past too, but in the end we mostly have data with pretty wide ranges (orders of magnitude) and couldn't really imagine manual scaling would be that great of a user experience.

**Comment by JulesAU** [comment]
Not explicit manual control; just automatically setting yMin, yMax according to the range of the data in the newly defined time period (after user changes the zoom).

Yep I suspect Pond will make this quite simple. I'll have a go at it. Thanks!

**Comment by tista3** [comment]
Thanks. I did not know about cropping.
So instead of this code, which set the min/max from entire timeseries:
```
<YAxis
    id="speed"
    label="speed"
    min={this.state.series.min("speed")}
    max={this.state.series.max("speed")}
    format=".1f" 
/>
```
I used the crop function and it autoscales Y axis while zooming:
```
<YAxis 
    id="speed"
    label="speed"
    min={this.state.series.crop(this.state.timerange).min("speed")}
    max={this.state.series.crop(this.state.timerange).max("speed")}
    format=".1f" 
/>
Hope this helps somebody else
```
