### ISSUE TITLE
Positioning charts on the page

### ISSUE THREAD

**Issue by mraak** [esnet/react-timeseries-charts#135]
All of the examples examples are stretch full screen, border to border of the page. In styling I see no docs in how to set up widths, heights, margins of the overall container of the page. And indeed when I used some of the charts from examples in my project the whole UI got messed up. 

Are there any docs or examples how to make text flow around the chart, or other positioning stuff?

**Comment by pjm17971** [comment]
I think the following should work to make a fixed size chart:

1) Don't use a `<Resizable>` around the top `<ChartContainer>`, this is what drives the width to be the width of the surrounding container (unless that's what you want, for instance if you are fitting into a bootstrap grid or flexbox).
2) Provide your own width to the `<ChartContainer width={300} ... >`
3) The height is driven by the heights in the `<ChartRow>` plus the bottom time axis.

Ultimately this width and height are props on the resulting `<svg>` block, so if your page can layout correctly with a fixed sized `<svg>` block within it, then it should be able to deal with a chart. Beyond that it's hard to anticipate all the ways that the chart could be inserted into a larger page.

If the above doesn't work, let me know.
