### ISSUE TITLE
Examples website doesn't work (WSOD)

### ISSUE THREAD

**Issue by qooban** [esnet/react-timeseries-charts#138]
This library looks like very suitable for the project which I am contributing now, so I would like to check and learn more about it from examples. Unfortunately it looks like something wrong with examples website. I get WSOD when I'm opening software.es.net/react-timeseries-charts . Is it general problem?

**Comment by pjm17971** [comment]
Hmm.. it seems to load ok for me, and it used widely. It does require SVG support in the target browser, so old IE doesn't work. Can you send me the browser/version you are using and any message that appears in the console?

**Comment by qooban** [comment]
Thanks for quick answer. 

I have tested now on Firefox 45.8.0 and on Google Chrome (56.0.2924.87).
I get such error in the console:
![Firefox](https://cloud.githubusercontent.com/assets/5202105/23937308/23a47308-0957-11e7-876b-556042f97963.PNG)
but on Google Chrome it works without problems, I get no errors in the console.

Maybe something wrong with this version of FF?

**Comment by qooban** [comment]
Yes, it looks like that version of FF was 'affected'. I installed the latest (52) and it works without problems. Previous version I used (45.8 ESR) must have not support all things necessary to render this site.

Anyway - I think we can close that issue. Once again - thanks, Peter, for express support. 
I'm going down into examples of that component to get to know if it can help in our project.
