### ISSUE TITLE
Missing examples in git

### ISSUE THREAD

**Issue by zvebbo** [esnet/react-timeseries-charts#139]
Firstly, I really like the look of this project and it seems to be fitting perfectly for us. 
I am currently trying to make a stacked area chart but having some troubles with the styling. The main problem is that I can't seem to figure out what columns should be.

http://software.es.net/react-timeseries-charts/#/example/continents?_k=oepr9u
columns={columns}

http://software.es.net/react-timeseries-charts/#/guide/style?_k=xmmlg3
 columns={{up: ["in"], down: ["out"]}} 
these labels seem arbitrary to me.

Is it possible to get the Stacked AreaCharts (and perhaps other missing examples) in the git repository?

**Comment by pjm17971** [comment]
The website is built directly from this repo. You can find all the samples here:
https://github.com/esnet/react-timeseries-charts/tree/master/src/website/examples

Specifically about columns, they are the columns in the Pond TimeSeries you pass into the AreaChart. Generally, a TimeSeries might look something like:

```
const series = new TimeSeries({
    name: "traffic",
    columns: ["traffic", "in", "out"],
    points: [
        ...
    ]
});
```

The up and down means which columns to stack upwards and which to stack downwards. The in and out are from the columns of the timeseries. 

Hope this helps. Let me know if you have problems with the above.

**Comment by zvebbo** [comment]
I realise now I was a bit to quick to ask (and a bit blind aswell I assume). 
Thank you very much for the quick reply! I managed to get things working correctly.

A quick question (maybe offtopic but I feel it's unnecessary to start a new thread if it is intended to work the way it is)
I want to show only years in the x-axis. And then I of course use the format="year" on the ChartContainer. That did not work however, and after looking through the source code I noticed it only checks the format-prop in "componentWillReceiveProps" in TimeAxis.js. 

So I needed to give new props after the chart had mounted in order for it to read the format prop. 
When I then added a <Rezisable> this did no longer work, because the chart renders a bit more slowly. 
So as for now I'm using a short setTimeout in order to set the format prop.

Maybe the props should be read when first constructing the chart?
Just a friendly thought. Keep up the good work!

**Comment by pjm17971** [comment]
No worries.

Can you paste the above into a new item? Sounds like a bug. There's a remaining piece of d3 rendering in the code there, but the aim is to eventually swap that out for a react solution. In the mean time, the above seems fixable.
