### ISSUE TITLE
EventChart zoom broken

### ISSUE THREAD

**Issue by beihl** [esnet/react-timeseries-charts#143]
I know this is experimental component, but ...

Zoom WAY in as far as possible. Becomes unresponsive

You can see it in example :
http://software.es.net/react-timeseries-charts/#/example/outages

**Comment by beihl** [comment]
So this seems to effect any `Chart` but can be avoided by setting `minDuration`, `maxTime`, `minTime` props on the `ChartContainer`.

**Comment by pjm17971** [comment]
Yes, I think you hit a lack of precision and so the calculations for the zoom and pan start failing. This is basically why those props exist on the `ChartContainer`. Sadly, I don't think there's any easy way to fix this, so I'm closing this.
