### ISSUE TITLE
Uncaught TypeError: Cannot read property 'color' of undefined

### ISSUE THREAD

**Issue by kevart** [esnet/react-timeseries-charts#144]
I have copied some code from the [examples](http://software.es.net/react-timeseries-charts/#/example/currency?_k=knve0l):

```
const legendStyles = styler([
  {key: "foo", color: "steelblue", width: 1, dashed: true},
  {key: "bar", color: "#F68B24", width: 2}
]);

```
And in my return function:

```
<Legend
        type="line"
        align="right"
        style={legendStyles}
        highlight={this.state.highlight}
        onHighlightChange={highlight => this.setState({highlight})}
        selection={this.state.selection}
        onSelectionChange={selection => this.setState({selection})}
        categories={[
            {key: "aud", label: "AUD", value: 33},
            {key: "euro", label: "Euro", value: 44}
        ]} />
```

The Legend doesn't get rendered and the console shows: 

**Uncaught TypeError: Cannot read property 'color' of undefined  styler.js:145**

"react-timeseries-charts": "^0.12.4",

**Comment by jtrshelley** [comment]
I have the same issue currently using basically any chart except the TimeRangeMarkers.

**Comment by pjm17971** [comment]
I think this is likely caused by the keys in the styler (above "foo" and "bar") not being the same as the category keys (above "aud" and "euro"). In other cases (other than the legend) that might similarly be because the styler keys are different from the columns in a timeseries.

**Comment by jtrshelley** [comment]
After I added the column title, I was able to eliminate the error, but the color still defaulted instead of using the color I specified.
