### ISSUE TITLE
Warning: Failed prop type: Invalid prop `trackerInfoValues` supplied to `ChartRow`.

### ISSUE THREAD

**Issue by kevart** [esnet/react-timeseries-charts#145]
I have copied the trackerInfo form this [example](http://software.es.net/react-timeseries-charts/#/guide/markers?_k=3udhbo) into my Chart. It seems to work, the tooltip is shown, but it still generates a warning in the console.
<img width="243" alt="screen shot 2017-04-03 at 10 48 07 pm" src="https://cloud.githubusercontent.com/assets/5118530/24642957/a1e60d72-18bf-11e7-8bdf-f86fca40496b.png">
<img width="1280" alt="screen shot 2017-04-03 at 10 48 58 pm" src="https://cloud.githubusercontent.com/assets/5118530/24642984/c3426f1a-18bf-11e7-9dbb-bcfa0752f008.png">

```
//globally defined
const trackerInfoValues = [
    {label: "Speed", value: 33},
    {label: "HR", value: 44}
];
```

```
// inside the render method
<ChartContainer
          timeRange={timeSeries.timerange()}
          width={1000}
          trackerPosition={this.state.tracker}
          onTrackerChanged={this.handleTrackerChanged}
        >
          <ChartRow
            height="350"
            trackerInfoValues={trackerInfoValues}
            trackerInfoHeight={50}
          >
            <YAxis id="axis1" label="" min={timeSeries.min()} max={timeSeries.max()} width="80" type="linear" format="$,.4f"/>
              <Charts>
                  <LineChart axis="axis1" series={timeSeries}/>
              </Charts>
          </ChartRow>
        </ChartContainer>
```

Additional question: How can I set, change, hide the _undefined_ (in the screenshot).

**Comment by nichliu** [comment]
{label: "Speed", value: 33},

should be string not number

{label: "Speed", value: "33"} 

This will work
