### ISSUE TITLE
styler failed

### ISSUE THREAD

**Issue by nichliu** [esnet/react-timeseries-charts#146]
I got "Uncaught TypeError: Cannot read property 'normal' of undefined" , after I put styler on LineChart, When I remove style on LineChart, the chart is show but without style

```

const chartStyler = styler([
    {key: "temperature", color: "#2ca02c", width: 1},
    {key: "humidity", color: "#9467bd", width: 2}
]);
<ChartContainer timeRange={temperatureChart.timerange()} >
    <ChartRow height="400" width={1000}>
        <YAxis
            id="temperature"
            label="Temperature"
            min={10}
            max={30}
            width="60"
            type="linear"
            align="left"
        />
        <Charts>
            <LineChart key="temperature" axis="temperature" series={temperatureChart} style={chartStyler} />
            <LineChart key="humidity" axis="humidity" series={humidityChart}  style={chartStyler} />
        </Charts>
        <YAxis
            id="humidity"
            label="Humidity"
            min={10}
            max={30}
            width="60"
            type="linear"
            align="right"
        />
    </ChartRow>
</ChartContainer>

**Comment by nichliu** [comment]
fixed, key setup was wrong

**Comment by Peege151** [comment]
@nichliu would you mind showing the fix?  I'm getting this with `<BarChart>`.  I'm taking the style keys directly from the example.

**Comment by pjm17971** [comment]
The style keys need to correspond to columns in the timeseries. That's usually the problem with these types of errors.

For example:
 * your columns in your series might be ["time", "temp", "humidity"]
 * then the keys in the styler need to be [{key: "temp", color: "red"}, {key: "humidity", color: "blue"}]
 * and you'd probably want to render the LineChart with columns={["temp", "humidity"]}
 * what you call the axis id (and axis prop in the LineChart is separate, but usually I just call them the same thing (e.g. temp and humidity)
