### ISSUE TITLE
Control tick count on YAxis

### ISSUE THREAD

**Issue by alcuadrado** [esnet/react-timeseries-charts#150]
Is it possible to display integer-only ticks in an `YAxis`? I tried using the `format` property, but it didn't work.

Here's my code for it: 

```jsx
<YAxis
  id="axisDonors"
  label="Investors"
  style={axisStyle}
  min={0}
  max={maxDonors}
  format="d"
  width="60"
  type="linear"
/>
```

Here's an example of what I'm getting (see the YAxis on the left):

![image](https://cloud.githubusercontent.com/assets/176499/25640997/44941c58-2f68-11e7-8966-8bfb8cf5fb98.png)

I'd like to have only 2 ticks: `1` and `2`.

Is it possible?

Thanks!

**Comment by pjm17971** [comment]
I think it will only be possible to control the format of the values, like you have on the left axis. The number of points are on the axis is automatically generated.

However, I don't think this would be hard to change. If you look at https://github.com/esnet/react-timeseries-charts/blob/master/src/components/YAxis.js#L183 this is where that happens. If you look just above that there's special handling for if the row is not very high and the number of ticks is defined. So, the idea would be to add a prop, maybe tickCount, and then in the above code block put in a conditional for if the tickCount is defined. Then just make sure it's in the propTypes at the bottom of that file.
