### ISSUE TITLE
Duplicate value when use scale time

### ISSUE THREAD

**Issue by christianweekend** [esnet/react-timeseries-charts#151]
can you help me why value time can be duplicate when i use tickformat 
in same moth like:
01-jan-2017 until 20-jan-2017
and when i did't use timeformat will display am or pm time
and after i use time format am or pm time change base on timeformat
so why can be like that?
i check data when i send still did't got any duplicate

![untitled](https://cloud.githubusercontent.com/assets/28341554/25653064/748ab720-3015-11e7-8425-8bdbdd1eafc9.png)

**Comment by pjm17971** [comment]
Well I suppose it is sub-dividing the time into 12 hour increments and your format is masking that by not differentiating between 2012-04-24 12:00 am and 2012-04-24 12:00 pm.

**Comment by pjm17971** [comment]
I'm not sure there's any action that can be taken on this, so I'm closing this issue.
