### ISSUE TITLE
Change Wind example ScatterChart prop from selection to selected to fix selection highlighting

### ISSUE THREAD

**Issue by christian-acuna** [esnet/react-timeseries-charts#154]
In the wind example, the ScatterChart component is passed selection instead of selected as outlined in the docs. After changing `selection` to `selected`, the selection functionality works when you click on an event. ScatterChart's PropTypes expect `selected` to be a string, but it should be an object. I'm happy to create a PR for this bug. 

After changing selection to selected.
![may-23-2017 15-58-56](https://cloud.githubusercontent.com/assets/7112158/26379990/d0d055f6-3fd0-11e7-9032-fc6196730c5c.gif)

<img width="1649" alt="screen shot 2017-05-23 at 4 02 13 pm" src="https://cloud.githubusercontent.com/assets/7112158/26380093/5c96ce80-3fd1-11e7-969a-71383cbec81e.png">

**Comment by pjm17971** [comment]
Thanks for the report. I just recently noticed this regression, too.
It would be awesome if you could submit a PR for it!
