### ISSUE TITLE
Feature Request/Question: Gantt Chart/Scatter Plot box shapes

### ISSUE THREAD

**Issue by lquinn2015** [esnet/react-timeseries-charts#157]
So have been working with these charts for a bit but I need something slightly different. So I have a Location, Time, and Duration data. With this data i need to be able to points like a scatter plot but instead of placing circles i need to be able to have a start place and graph a rectangle at the start and going to the end time based on location. I was looking at the box chart but it seemed as thought you could only have one box object per a vertical y line. I could maybe draw multiple Y Axis for each location but this seems like a poor way of doing things because i can have multiple kinda of events happening so the data is not easily dividable. Maybe this is already possible or you have and idea of how to do this all help is appreciated. Theres a poorly drawn picture below to show what i mean 

 
![image](https://user-images.githubusercontent.com/16884061/27101132-79ccd930-504e-11e7-801a-96d917b36929.png)

**Comment by pjm17971** [comment]
I guess if I was going to do that, I'd firstly use multiple rows, one for each location.

For each row, it's relatively easy to plugin your own component to render it. Simply make a new React component and render a <g /> SVG for testing. Call it RectangleChart or whatever, then put it into the <Charts> group like any other chart. Now look at the props passed into it. You will see the scales and sizes that you are expected to render. After that, it's up to you to determine what props to pass in and how you are going to render into the area given to you, with the scales supplied.

**Comment by pjm17971** [comment]
Also, you can look at the EventChart, that may be enough?

**Comment by lquinn2015** [comment]
Thanks for your help I hope I am not being to bothersome. So I am trying to make changes to the Scatter plot code so that it will render rects instead of circles and see if i can use a TimeRange timeseires so that i can set the width of the rect equal to the difference of start and end and scale the result with the timescale(hopefully that is legal). Right now though I am getting stuck with building a TimeSeries using TimeRange I am doing the following but end up with an error like isChronological is null type error...
```
			var t = new TimeRange(time, endTime);
			ptns.push([
				new TimeRange(time, endTime),
				height + (Math.random() * 2.4 -2.5)* WOBBLE_FACTOR - .01,
				count,
				species,
				color
			]);

	series2 = new TimeSeries({
		name: "Locats",
		columns: ["timeRange", "locNum", "count", "species", "color"],
		ptns
	});
```

I know that all the parameters with the exception of timeRange are setup right and that the error happens on series2's creation but I dumbfounded as to what is causing it. Any thoughts

**Comment by pjm17971** [comment]
You can build it like that, but instead of an actual TimeRange in there, I think you want a simple [t1, t2] array. And the first column name is "timerange".

Alternatively, this example builds a TimeSeries using TimeRanges:
https://github.com/esnet/react-timeseries-charts/blob/master/src/website/examples/outages/Index.js#L76

It's possible that an easier path is to make the EventChart code more flexible, since it's already in the business of rendering rectangles based on a TimeSeries of TimeRangeEvents...

**Comment by pjm17971** [comment]
I'm not sure this is well enough defined a request to keep open.
