### ISSUE TITLE
Do you know how can we resolve this issue reactBoilerplateDeps.dll.js:178643 Uncaught TypeError: (0 , _styledComponents2.default) is not a function

### ISSUE THREAD

**Issue by prajwal78** [esnet/react-timeseries-charts#158]

**Comment by pjm17971** [comment]
Hmmm... I don't think that error is obviously coming from this library. But in general an error like that would probably indicate a build issue. I don't know anything about either react boiler plate or styled components, so I'm not sure I can help. Sorry.
