### ISSUE TITLE
Support tooltips in barcharts

### ISSUE THREAD

**Issue by pjm17971** [esnet/react-timeseries-charts#16]
It would be nice if you could hover over points on a line chart or bars on a bar chart and get information about that element. Unfortunately the tracker/eventrect code is eating those events. We need to look at the event handling code and make a distinction between pan/zoom and tracker code, and hover over element handling.

**Comment by gfoiani** [comment]
+1

**Comment by gfoiani** [comment]
In the issue text, besides bar charts, you also mentioned line charts. Do tooltips work for line charts or only for bar charts?

**Comment by pjm17971** [comment]
Re: the line charts, yeah, it's true, I only added support for the bar charts. We generally use the tracker and then put the value and timestamp being hovered over alongside the chart. e.g at the bottom of this page:

[https://my.es.net/](https://my.es.net/)

The reason was it was more flexible when there was multiple things you wanted to show based on the mouse over position. But it's still something I want to do.

My current thinking is that support for this would be an extension to the tracker line, which has a separate issue: #31. Feel free to add thoughts there.
