### ISSUE TITLE
Links to the example source code not working

### ISSUE THREAD

**Issue by m-h-t** [esnet/react-timeseries-charts#172]
See e.g.: http://software.es.net/react-timeseries-charts/#example/weather

**Comment by pjm17971** [comment]
@m-h-t: thanks for reporting this, looks like it snuck in with a PR last week.
@sartaj10: can you take a look at this?

**Comment by miccferr** [comment]
In the meantime, just as a reference for people looking for the examples (see #139) the folder is currently [here](https://github.com/esnet/react-timeseries-charts/tree/master/src/website/packages/charts/examples/)

**Comment by pjm17971** [comment]
@miccferr thanks, we will deploy a fixed website soon!

**Comment by kevando** [comment]
I would also find it super helpful to have a concise example that demonstrates how to generate a simple time series all in one file. I am very new to this concept.
