### ISSUE TITLE
To improve performance of Cycling example

### ISSUE THREAD

**Issue by wither23265fa** [esnet/react-timeseries-charts#174]
I try to use Cycling example - ChannelChart, it's already had been worked, but its performance is not good,I need three chart row of ChannelChart, and another chart row of Brush. I have the dynamic data which need to keep transmit for React, Most volume of the data would be 40,000 pieces(it means that has 4 Two-Dimensional Arrays whose length is 40,000), but if the data volume is bigger than 10,000, then it would be slowly to loading, high CPU usage, and the tracker also has this problem.

Is there anyway to improve it's performance, or just reduce my data volume or update frequency?

**Comment by Fxlr8** [comment]
This is all about SVG and performance. I tried about 10 different SVG/d3/react based charting libraries and they all suffer performance issues when you try to stuff significant amount of data into them. Also, I noticed that retina screen makes this situation even worse. Unfortunately, the fastest charts are canvas based. A possible workaround (not tested) would be to filter your data set to only render the visible part of data. Also, i would suggest to batch data when a lot of points are visible. Fewer points = more speed.

**Comment by wither23265fa** [comment]
Got it! I'm designing an algorithm to filter my data set right now, 
Thank you to let me make sure how to complete it!

**Comment by pjm17971** [comment]
@wither23265fa: Sorry I'm late to this discussion (on vacation). So, yes, what @Fxlr8 said is basically true, there's only so much SVG can do. It would be cool to be able to render to canvas, but I think this is still a losing battle. It is better to deal with down sampling your data to reasonable screen resolution first.

This is part of the reason why the library has a semi-real timeseries library (pond.js) behind it. At least we've found that useful. One way of filtering data is to use a fixed window rollup. Generally you want the windowing fixed so you can pan the window and not have artifacts of the data moving between windows. But there's other approaches.

Here's some code:
```js
const timeseries = new TimeSeries(data);
const downsampled = timeseries.fixedWindowRollup({
    windowSize: "5m",
    aggregation: {value: {value: avg()}}
});
```

See the [pond.js](http://software.es.net/pond) docs for more options.

You can use the current timerange and several pre-baked rollup timeseries to transition between resolutions if you need to zoom. Also, make sure to crop your timeseries to the timerange you are displaying. That will improve some aspects of performance as well.

We also go a step further and actually do this on the backend and then send pieces of timeseries at reasonable resolutions, which we merge together. (1 day chunks of 30 second averages, transitioning to 7 day chunks of 5 minute averages and so on...).

**Comment by wither23265fa** [comment]
@pjm17971 I had been trying fixed window rollup, it is good for display my data set and convenience to choose the time interval which I want to show, but its performance still not good when the tracker or data set is changing. Well, I also use '.crop' to slice it, but its interval is mutable, sometimes it is too many points to display, so I sample my data set by the following algorithm:

    1. Check if (point.length <= limit.length) Go to Step 8
    2. Calculate time interval      
    3. Check if (time range <= window size) Go to Step 5
    4. Slice data
    5. Check if (time interval <= default interval) Go to step 8
    6. Calculate time scale
    7. Reduce data set by time scale
    8. Put data set into outputPoint

When I need to reduce data set by scale, I will see the different value in the point which have the same time. Because the newest time will keep moving, and cluster which zoom by timeScale will change after the newest time updated. So, I should let member of cluster immutable.

The solution of my mind is regulating the cluster time start and time end,
But I still have no good idea to implement it.
