### ISSUE TITLE
enable flag ?

### ISSUE THREAD

**Issue by tech-a-go-go** [esnet/react-timeseries-charts#183]
Hi,

Do charts have something like an enable property so that I can make them to be visible or invisible ??

Cheers

**Comment by sartaj10** [comment]
@pjm17971 is this related to Issue #116 ?

**Comment by pjm17971** [comment]
@sartaj10: perhaps related, I'm not sure of the exact use case here. @tech-a-go-go?

I've imagined since the beginning of this library that it would be nice to have a `hide` prop on both the ChartRow and Charts themselves, because often you want to toggle them with some other UI or page state. You can do it now by re-rendering with that part missing, but in practice it's kind of awkward to do it that way. This would be easy to implement on the row itself, since it's already inspecting the props of the child charts.

**Comment by tech-a-go-go** [comment]
Hi,

My chart component is too fat now ;( so it's kinda hard to re-render with that part missing.
( 3 line charts and a box chart share a timeline and they all are rendered with a single render method. ) 
But it's still easy to do this.setState({myBoxChartEnable: false}) if it's possible.

Yes, I know it's my fault... if I've implemented something like separating the render method to 2 or 3 methods, I could easily re-render with that part missing.

Thanks

**Comment by iabw** [comment]
I implemented this on a category by category basis, allowing the Legend to toggle them, and hide the row if none are visible.

Here's some simplified example code (probably non-functional) to give you the gist.

```jsx
class ChartWrapper extends React.Component {

  constructor(props) {
    super(props);

    this.state = {
      categories: props.categories,
      style: styler(props.categories.map(x => x.styles))
    }
  }

  // allows toggling whether a category is turned on by clicking it on the legend
  onLegendSelectionChange(key) {
    const category = this.state.categories.find((category) => category.key === key);
    category.enabled = !category.enabled;

    this.setState({
      categories: this.state.categories,
      style: styler(this.state.categories.map(x => x.styles))
    });
  }

  render() {
    const enabledColumns = this.state.categories.filter((category) => category.enabled);

    return (
      <div>
        <ChartLegend
          categories={this.state.categories}
          style={this.state.style}
          onSelectionChange={this.onLegendSelectionChange}
        />
        <ChartContainer>
          { enabledColumns.length ?
            <ChartRow
              <Charts>
                <LineChart
                  columns={enabledColumns.map(x => x.key)}
                  style={this.state.style}
                />
              </Charts>
            </ChartRow>
          : <span/> }
        </ChartContainer>
      </div>
    );
  }
}
```

Unfortunately I can't provide a guaranteed working minimal example atm, as I'm also adding on a bunch of interactions and re-draw optimizations and haven't been keeping a clean commit history.

---

I'm hoping to boil down some of the changes and wrapping classes I've made into PRs for TSC after another week of sorting it all out, and this behavior will be included in the first round of those. Working on this full-time for my day-job, and have initial agreement to merge back upstream. We'll be reviewing PR permission on a case by case basis, so stay tuned! 🤞

**Comment by pjm17971** [comment]
This is now supported on Charts, ChartRows and Axis
