### ISSUE TITLE
Drag to Zoom via flag on ChartContainer

### ISSUE THREAD

**Issue by iabw** [esnet/react-timeseries-charts#184]
The same way you can have `<ChartContainer enablePanZoom={true}>`, it'd be nice to allow `<ChartContainer enableDragZoom={true}>`.

I made `enableDragZoom=true` work by adding some code into the EventHandler component next to where the enablePanZoom flag is handled in mouseup/down/move.

After that, I saw #87 and that it was closed via #91 adding a hook on the Brush when it completes, but without investigation was unclear how exactly one might use that. It seemed like it would involve adding a Brush component and implementing a callback, which seems complicated compared to the simplicity of `enablePanZoom=true`.

Would you like to see a PR for this simplified drag to zoom option? Or do you feel that #91 covers it? If #91 covers it, can it can be added into the examples?

**Comment by pjm17971** [comment]
Can you show an example of what that would look like? I can't really visualize. You would drag the mouse across the chart and it would zoom?

**Comment by iabw** [comment]
Yep. Looks like this -
![dragtozoom-gif](https://user-images.githubusercontent.com/1054569/31302628-c914ed96-aac8-11e7-8578-93858ea1f862.gif)

PR also attached.

---

It also adds a y value back into the mousemove handler at [line 266](https://github.com/esnet/react-timeseries-charts/pull/186/files#diff-939515966176cccc28855faead424e41R266). I found this to be helpful for pulling all my event handling up into the ChartContainer instead of in the individual charts, which let me do things like provide tooltips for ScatterCharts rendered underneath other ScatterCharts.

**Comment by pjm17971** [comment]
This is pretty cool. I'm wondering if you still plan to add a new PR for it? Or should I close this?

**Comment by iabw** [comment]
#187 has the final isolated version of this feature, although should probably add some documentation for it. I could do that this week.

**Comment by sartaj10** [comment]
Thanks for the PR! @iabw
