### ISSUE TITLE
Brush's mouseup doesn't detect if off-element

### ISSUE THREAD

**Issue by therealtbs** [esnet/react-timeseries-charts#188]
When releasing the mouse while outside the chart while dragging the Brush(Overlay), the event isn't handled.
The appropriate code is only in the `handleHandleMouseDown` function,
when it should be in `handleOverlayMouseDown` and `handleBrushMouseDown` as well.
I have already made the change in [my fork](https://github.com/therealtbs/react-timeseries-charts/tree/fix-brush-mouseup), so the PR would be ready when you give the go-ahead.

**Comment by pjm17971** [comment]
Sounds like a good change, please submit a PR and I'll take a look.
