### ISSUE TITLE
How to display chart data for many days into one view?

### ISSUE THREAD

**Issue by tsvetann** [esnet/react-timeseries-charts#190]
What I would like to achieve is the following:

I have sensor data worth of 20 days but I would like to display an aggregated view of all 20 days into one shot. That means if day 1 has a value at 09:00, day 2 has a value at 09:02, day 3 has a value at 09:30 I would like to display all these values into one view. On the horizontal axis to display only the hours without any dates. Is it possible to aggregate all my data into something like scatter chart? Any guidance would be highly appreciated.

Thx in advance

**Comment by pjm17971** [comment]
Maybe you can use the `format` prop on the `ChartContainer`, which I think can take a d3.format, to control what the actual format looks like (i.e. show just the time). You'd have to put all the points into one actual day though like Jan 1, 1970. I'm not sure what else to suggest (and sorry for the slow response on this).
