### ISSUE TITLE
How to add another line/column to realtime chart ?

### ISSUE THREAD

**Issue by limsan** [esnet/react-timeseries-charts#193]
in the Realtime chart example, it uses one line data, I am struggling to add another data stream/ line to the chart ? 
Can you please give me a hint? a small example
I tried array: TimeEvent(t,  [2, 100])
and also transform the array of timeEvent Objects to array of Points and create new timeSeries
const eventSeries = new TimeSeries({
          name: "raw",
          columns: ['time', 'a', 'b'],
          points: flatData,
      });
Still shows error :Error: <circle> attribute cy: Expected length, "NaN".

**Comment by pjm17971** [comment]
Did you figure this out?
