### ISSUE TITLE
Enable the ability to ignore null data points in `<ScatterChart />`

### ISSUE THREAD

**Issue by nphoff** [esnet/react-timeseries-charts#197]
Hello!

I have some data that I need to plot that looks like this:
```
[
  {"time":1483347600000,"data":{"prediction":42.34860610961914,"data":null}},
  {"time":1483434000000,"data":{"prediction":42.34860610961914,"data":null}},
  {"time":1483520400000,"data":{"data":45.1,"prediction":43.43721008300781}}
]
```

As you can see, the `data` field is `null` for a few data points, but is populated properly in some places.

As it's currently implemented, the `ScatterChart` component will plot zeroes for null values (https://github.com/esnet/react-timeseries-charts/blob/master/src/components/ScatterChart.js#L210)

My suggestion is that another prop is passed in to `ScatterChart`, something like `ignoreNulls` or `ignoreBadPoints`, and with that flag on, we could do some filtering like what's done in `LineChart` (https://github.com/esnet/react-timeseries-charts/blob/master/src/components/LineChart.js#L213)

I'm pretty unfamiliar with what the preferred API would be like for this, so I'm very open to pushback or other ideas. If folks are good with my suggestion, I'd be happy to write up the PR for this.

Thanks!

**Comment by hillmark** [comment]
It could be a useful addition. My current workaround is:

`radius={(event, column) => event.get(column) ? 1 : 0}`
or,
`radius={(event, column) => event.get(column) ? 2 : null}`

One thing I like about my method is the flexibility to do something other than just ignore null values, i.e. render at a different size, but ignoring `null` values altogether might bring performance benefits.

**Comment by pjm17971** [comment]
An option is `timeseries.clean("data")`.
