### ISSUE TITLE
Expose y (and x) values on mouse hover

### ISSUE THREAD

**Issue by iabw** [esnet/react-timeseries-charts#199]
Currently, the EventHandler only returns the time the user is hovering at (which is passed directly into `onTrackerChanged` in ChartContainer's handleMouseMove callback.

It would be useful to expose the raw x value (not just the time) and also the y value so that we can write our own mousemove handlers if wanted.

One example is for multiple scattercharts, which currently only register mousemove events on the top-most chart. By exposing the x and y values, we can loop over all the timeseries to find the nearest event directly, instead of relying on svg hover events.

**Comment by nbrady-techempower** [comment]
Something like this would be great. Being able to enable a `horizontalTrackerPosition` for control over showing either or both at the same time would be especially helpful.
