### ISSUE TITLE
What is the unit of time for the TimeSeries object?

### ISSUE THREAD

**Issue by lch2001** [esnet/react-timeseries-charts#209]
```
const series = timeSeries({
    name: "sensor_data",
    columns: ["time", "sensor", "status"],
    points: [
        [1400425947000, 3, "ok"],
        [1400425948000, 8, "high"],
        [1400425949000, 2, "low"],
        [1400425950000, 3, "ok"],
        ...
    ]
});
```

e.g 1400425947000, 1400425948000.

How would I convert DD/MM/YYYY to that? I plan on only plotting by the day.

**Comment by pjm17971** [comment]
The value is millisecond since Jan 1 1970 UTC (unix epoch).

```
> const d = new Date("2018-01-22")
undefined
> d
2018-01-22T00:00:00.000Z
> d.getTime()
1516579200000
> 
```

**Comment by rweller59** [comment]
Is it required to provide time in this (1516579200000) format? - trying to avoid lots of conversions.

**Comment by pjm17971** [comment]
Yes. But if you have a `Date` `d` then `d.getTime()` is very inexpensive.

**Comment by rweller59** [comment]
thanks, was just trying to avoid looping through all arrays to change the format
