### ISSUE TITLE
Baseline label not positioned correctly

### ISSUE THREAD

**Issue by ethanroday** [esnet/react-timeseries-charts#210]
When adding a baseline close to the maximum of an axis, the baseline label is cut off by the top of the chart:
![image](https://user-images.githubusercontent.com/896670/35288702-50e95152-001a-11e8-8d3f-87923fc5a5bc.png)
In this case, the label could be placed below the baseline, or the max of the axis could be automatically adjusted.

In general, it would also be nice to have more control over the positioning and styling of the baseline label, as well as the ability to place it fully to the right of the chart.

**Comment by pjm17971** [comment]
Agreed, it could do a lot more than it does right now. And be smarter about the issue you've shown. Thanks for reporting.
