### ISSUE TITLE
Not able to control  the width of the graph

### ISSUE THREAD

**Issue by rainitesh** [esnet/react-timeseries-charts#214]
Somehow I am not able to change the width of the graph by changing the `width` property for `<ChartContainer>`

My panel width is small and would like my graph to fit within it but seems like the data on the right is hidden at the moment. 

Here's the code and image below
```
return (
        <Resizable>
          <ChartContainer timeRange={series.range()} format="%H:%M" widht={300}>
            <ChartRow height="250">
              <YAxis
                id="price"
                label="dB"
                type="linear"
                min={series.min()}
                max={series.max()}
                width="60"
                format=".2f"
              />
              <Charts>
                <LineChart axis="price" series={series} style={style} />
                <Baseline
                  axis="price"
                  style={baselineStyleLite}
                  value={series.avg()}
                />
              </Charts>
            </ChartRow>
          </ChartContainer>
        </Resizable>
      );
    } else {
      return null;
    }
```

![image](https://user-images.githubusercontent.com/16216239/35844920-facdf322-0b63-11e8-94aa-f946fed761fa.png)

**Comment by pjm17971** [comment]
Typo?
```
widht={300}
```
However, the `width` will be injected from the `Resizable`. That will take the containing div's width and supply it down to the chart. That's usually the way to go unless for some reason you want to fix the chart width to a specific size.

**Comment by rainitesh** [comment]
Sorry about the typo in the issue. I tried passing typo to both `Resizable` and `Chartcontainer` but it does not seem to make any difference for me. I passed width={300} but you can see the svg values below. I just want to fit the graph inside the panel and somehow at the moment I am losing the graph on the right.

![image](https://user-images.githubusercontent.com/16216239/35888135-ce602878-0bea-11e8-8810-9281738c87ce.png)

**Comment by pjm17971** [comment]
If you want it to size to the div you put it in, you should be able to use `Resizable` around the `ChartContainer`, but don't pass in width to either the resizable or the chart container. It will figure it out. But verify that outer div in your layout (graphPanel?)  is indeed sizing to the width you want.

If you want a fixed sized chart (e.g. always 300px), remove the `Resizable` from the outside and pass `width={300}` into the `ChartContainer`.

We typically use it within a bootstrap row/column, but it's hard to tell from your screenshot what css might be being applied and why you are having trouble.

**Comment by pjm17971** [comment]
Did you ever figure this out? Closing this issue for now.
