### ISSUE TITLE
Example should include a `columns` prop in the line chart

### ISSUE THREAD

**Issue by goleary** [esnet/react-timeseries-charts#215]
in the docs it makes no mention of the column property for `<LineChart>`
![image](https://user-images.githubusercontent.com/16123225/35846983-a1f2b5bc-0acd-11e8-8cfd-e0831c03129f.png) - http://software.es.net/react-timeseries-charts/#/guide/start

I spent some time trying to figure why my line wasn't showing up and this could have been prevented if the example above included `column={['aud']}` or the like.

**Comment by pjm17971** [comment]
Makes sense. Thanks for pointing this out.

**Comment by goleary** [comment]
thanks!

**Comment by daniel-wer** [comment]
For anyone stumbling upon this issue, the prop ist actually called `columns`, the documentation is missing the plural `s`.

The documentation fix from this issue is also missing in the Readme, unfortunately, which is why I was struck by it in the first place.
