### ISSUE TITLE
Make minimum BarChart bar height of 1 pixel optional

### ISSUE THREAD

**Issue by dirkdevriendt** [esnet/react-timeseries-charts#218]
I see there was already a PR for making it configurable, but this did not get accepted it seems?
https://github.com/esnet/react-timeseries-charts/pull/195

I was trying to show monitoring and forecasted stacked bar data in different time series on the same chart, but the min 1 pixel height makes this impossible (read: ugly :-))

**Comment by pjm17971** [comment]
Seems reasonable. 

I'm not sure about that PR, it seems like he closed it right after he opened it. Not sure why.

**Comment by dirkdevriendt** [comment]
Nice, thanks!
Can you recover the PR or do you want me to recreate it / is there something else I can do?
