### ISSUE TITLE
Control X-axis tick count

### ISSUE THREAD

**Issue by davegravy** [esnet/react-timeseries-charts#220]
I'm using a `ChartContainer` within `Resizable`. On larger container widths, tick spacing is fine, but as I shrink the window the tick labels overlap and look bad. The cycling example which I used as my template seems to have this problem too albeit at much smaller window widths since the labels are tiny. 

Is there a way to define a function for # of tick marks or spacing in order to make the chart responsive? 

FWIW my labels are 14 characters.

**Comment by pjm17971** [comment]
No, it isn't possible to control the time axis in that way. Currently the x-axis is generated by d3 but we're updating this code with our own code (react-axis) so this might be possible in the future.  Sorry.

**Comment by NashBaughn** [comment]
When will this be completed? I am using your package, it is great, but has very low aesthetic appeal when trying to present time series data with the generic scope filters (day, week, month, year, all). It just doest looks great. I would be happy to contribute.
