### ISSUE TITLE
Help connecting api data to chart

### ISSUE THREAD

**Issue by rweller59** [esnet/react-timeseries-charts#221]
very excited to discover this library but having a few problems coming up to speed. Could you provide some input/example on connecting api data to graph data in react-redux environment - specifically attaching new data to existing graph

**Comment by pjm17971** [comment]
We don't use redux, so I'm probably not the best person to answer. But in general what you want is to maintain you current data as a `TimeSeries` as state or passed in props (e.g. from redux) and then just re-render with that. In addition you may want to maintain an active `TimeRange` (if you are going to allow the user to pan and zoom). Or just get it from the series.

We use the charts code in several ways:
 * in some cases we have a wrapper component that is our dataLoader. It manages the life cycle of the actual data fetch and when it is done loaded supplies the chart it wraps with the loaded series.
 * in pan/zoom cases we pre-cache a tile of timeseries on the server side and then load that, merging these tiles as needed

All of the examples I think have a series that's just loaded in via a json file, but there's no reason it can't just be a prop that comes from somewhere else. This is really very dependent on your circumstance.

**Comment by rweller59** [comment]
thanks. working my way towards that solution now

**Comment by davegravy** [comment]
I'm working on doing the same thing. 

My API is paged, and currently as a page gets added, the data gets appended to what's already in the Redux store, and I reprocess the WHOLE set, feeding it into the component state as a new TimeSeries. It's wasteful.

My plan is to instead store each page's data under a separate page ID key, track in the component state what page IDs have already been handled, and process each new page into a new TimeSeries, merging it into the master TimeSeries via [timeSeriesListMerge](https://esnet-pondjs.appspot.com/#/TimeSeries.timeSeriesListMerge)

Seem like a reasonable approach?
