### ISSUE TITLE
Multiple Brushes

### ISSUE THREAD

**Issue by barbaragomes** [esnet/react-timeseries-charts#222]
Hey There,

Is there a way to allow the user to draw and change multiple brushes?

I have tried adding 2 brushes to the same Chart but each Brush creates an overlay `g` component, which blocks the brushes behind the last one from being modified by the user.

Is there something that I'm missing or it is not supported?

Thanks

**Comment by pjm17971** [comment]
No, that isn't supported. Can I ask what the goal is? Are you trying to use brushes to let the user define multiple selections or something? I'm interesting in what the use case is. The brush was added for overview selection, but I know people have used it for other things.

**Comment by barbaragomes** [comment]
@pjm17971 I'm working on a tool where the user will be able to annotate different periods of the chart and associate some information to it.

I was looking into the Brush code and I was thinking I could modify it to work with an array of timeranges, which would all be rendered in the same overlay. 

Thank you for your reply!

**Comment by pjm17971** [comment]
That sounds like a great change. Can you make a PR for the change if you get it working?

**Comment by barbaragomes** [comment]
Sure thing. I will make a PR if I get it working.

**Comment by barbaragomes** [comment]
@pjm17971 I've made the changes to the Brush component itself, should I create a new component? Maybe an `Annotation` component or any other name you suggest calling it?

**Comment by barbaragomes** [comment]
I'm asking that because my changes are breaking changes, since now instead of `timeRange` and `style prop it expects a `timeRanges` and `styles`

**Comment by pjm17971** [comment]
Yeah, that makes sense. Maybe `MultiBrush`?

**Comment by barbaragomes** [comment]
I have created the PR but I wasnt sure if it should include the `/lib` files change. 

The component should work in the same way as the Brush component except the following changes:

1. **allowFreeDrawing** New prop that allows the user to keep drawing new brushes (default: `true`). If set to false, the user will be able to draw only if the last position of the `timeRanges` prop is null.
2. `timeRange` --> `timeRanges` and it is an array of TimeRange
3. `style` --> `styles` where each key in the object should match an index position in `timeRanges` prop

Hope it meet your expectations

**Comment by sartaj10** [comment]
@barbaragomes Can you demonstrate the MultiBrush component in action in the case of your example?
