### ISSUE TITLE
How do I determine width of LineChart component

### ISSUE THREAD

**Issue by davegravy** [esnet/react-timeseries-charts#232]
I have the following structure:

```
<Resizeable ref="resizeable>
  <ChartContainer>
     <ChartRow>
       <YAxis/>
       <Charts>
         <LineChart ref="linechart"/>
       </Charts>
       <ValueAxis/>
     </ChartRow>
  </ChartContainer>
</Resizeable>
```

I have redux actions which fire on window resize and I can accurately determine the outer chart width using `this.refs.resizeable.container.offsetWidth` however I want just the width of the inner LineChart. 

I tried `this.refs.linechart.props.width` but the value is outdated (it is the width before the resize, whereas resizeable ref gives me current width accurately).

I suppose I could calculate the outer width minus the width properties passed to the other components (YAxis and ValueAxis) but that seems like an ugly solution. Any ideas?

**Comment by pjm17971** [comment]
Yeah, this is related to #223. Until that's fixed, subtracting off the axis widths (and offset if one is set), will do the trick. Sorry.
