### ISSUE TITLE
Charts not rendering properly when using Webpack

### ISSUE THREAD

**Issue by rweller59** [esnet/react-timeseries-charts#233]
Had a need to incorporate webpack and have not been able to get charts to render since. All I get is a labeled x-axis and nothing else.  Have tried with previously working charts along with the samples . Have tried with multiple working versions of webpack projects

Any suggestions or help would be appreciated.

**Comment by sgoudelis** [comment]
Any luck with this issue ? I 've been having the same issue.

**Comment by rweller59** [comment]
I have not made any progress.  I am currently working with the library outside of webpack, hoping someone will provide input to help solve the solution. I'm assuming that it is a webpack configuration issue.

**Comment by pjm17971** [comment]
There's not enough information here for me to debug your webpack config. The only thing I can think of is that it needs to load css. One option is to use create-react-app. I know for sure that config will work.

**Comment by rweller59** [comment]
Graphs work fine with create-react-app. I've attached webpack config if you wouldn't mind taking a quick look. I've actually got multiple config files that I've tried although I am a webpack novice so probably making the same mistakes on all of them...
[webpack.config.development.txt](https://github.com/esnet/react-timeseries-charts/files/1829492/webpack.config.development.txt)

**Comment by pjm17971** [comment]
Do you get any errors?

**Comment by rweller59** [comment]
no errors, just the x-axis rendering. same component I used in the create-react-app

**Comment by tomstaijen** [comment]
Had the same problem. Setting NODE_ENV to production fixed it for me too. 

Doesn't seem to be just a css problem though. The x-axis is rendered just fine. There's no line data or y-axis data in the svg.

**Comment by pjm17971** [comment]
Thanks for all this, it's something to go on at least. I don't think it's to do with the registerServiceWorker. That's used by the docs website (create-react-app). Do you know if there's a react version that this started to happen in?

**Comment by pors** [comment]
We are using 15.6.2, but haven't updated it recently.

**Comment by EmpireJones** [comment]
Same issue here; graphs only work with NODE_ENV set to production. I'm using react 16.2.0

**Comment by karolk** [comment]
Inside ChartContainer there is a check:
`if (childRow.type === _ChartRow2.default) {`
and and inside this conditional you proceed to create ChartRows. Problem is that this never matches for me, although the sources look identical:
![chartrow](https://user-images.githubusercontent.com/224933/39134184-eadf59b6-470d-11e8-8e6c-f4a33381e84c.PNG)

I don't yet know why these 2 don't match but my guess is it could be because of react-hot-loader wrapping React components in wrapper components.

**Comment by pjm17971** [comment]
Usually this kind of thing is because you have two versions of the charts code loaded somehow.

**Comment by pjm17971** [comment]
For this issue in general, is anyone able to make a small example showing this issue. If so, I can try to figure out why this doesn't work.

**Comment by pors** [comment]
> Usually this kind of thing is because you have two versions of the charts code loaded somehow.

@pjm17971 is there a way to test if this is the case?

**Comment by karolk** [comment]
So I made a single change in my webpack conf:
```
  plugins: [
    // new webpack.HotModuleReplacementPlugin(),
```
and the chart started to work. The way hot replacement works is it swaps components for wrapped versions and I believe this is why this identity check fails.

**Comment by pjm17971** [comment]
Is the solution to use hot loader's `areComponentEqual()` function instead?

**Comment by karolk** [comment]
I am not a lib author but that's my understanding: to support react-hot-loader you need to have it as a dependency and use this util. It does the right thing in production and you can install is as normal dependency. 
> Note: You can safely install react-hot-loader as a regular dependency instead of a dev dependency as it automatically ensures it is not executed in production and the footprint is minimal.

**Comment by pors** [comment]
I can confirm that in our case it is also related to react-hot-loader.

**Comment by pjm17971** [comment]
@sartaj10 is going to take a look at this in the coming week and see if we can fix this. Thanks for the comments on this one, I think we're close to an answer here.

**Comment by sartaj10** [comment]
@rweller59 @pors @tomstaijen @EmpireJones @karolk 
I have a fix in the branch `fix-webpack`. Can you use that version in your package.json and see if that fixes your issue

Just replace this in your package.json
`"react-timeseries-charts": "git+https://github.com/esnet/react-timeseries-charts.git#fix-webpack"`

**Comment by sartaj10** [comment]
There's a small example to this as well - https://github.com/esnet/charts-webpack

**Comment by pors** [comment]
@sartaj10 the fix works for me, thanks!

**Comment by pors** [comment]
@sartaj10 is this fix included in the release 0.14.0? I just tried it, but I got the original problem: with the webpack hot module reloader I only see the x-axis.

**Comment by pjm17971** [comment]
@pors this will be in the next release (0.15.x)

**Comment by ethanroday** [comment]
Also commented in #305, but I guess it's more appropriate here:

> I'm seeing this as well on v0.15.5 from a regular, non-Electron Webpack config. If I disable HMR the problem goes away. Other version info:
> React: 16.6.3
> React HMR: 4.3.12
> Webpack: 4.20.2

**Comment by ethanroday** [comment]
Here's an example repository to illustrate the issue: https://github.com/ethanroday/react-timeseries-charts-233.

On dev build:
![image](https://user-images.githubusercontent.com/896670/49891621-d3648900-fdfb-11e8-8edf-42e5a4a7d8f1.png)

On production build:
![image](https://user-images.githubusercontent.com/896670/49891641-dcedf100-fdfb-11e8-8ac9-fb64100e4e53.png)

Would vote for this issue to be reopened.

**Comment by hirro** [comment]
I also had this problem, even with latest version of the library and react-hot-loader("4.12.15").

The following solved the problem for me:

```
const ColdResizable = cold(Resizable);
const ColdChartContainer = cold(ChartContainer);
const ColdChartRow = cold(ChartRow);
const ColdYAxis = cold(YAxis);
const ColdAreaChart = cold(AreaChart);
const ColdCharts = cold(Charts);
```

Then I used the library as usual but with Cold prefixes.
