### ISSUE TITLE
Show data gaps in AreaCharts

### ISSUE THREAD

**Issue by sgoudelis** [esnet/react-timeseries-charts#242]
Hello,

I am using an AreaChart and I would like to visualize a gap in my data. Currently the date gap between datapoints is basically a slope to the next datapoint. Is there a way to visualize the gap that exists between to arbitrary  datapoints using an AreaChart? Should I use another chart type ?

**Comment by luke-unifymonitor** [comment]
Hi, for what it's worth - I'm also looking for this feature.  I need to handle null values on a LineChart?

Great library by the way.

Thanks.

**Comment by pjm17971** [comment]
The library will do this automatically for a `LineChart` but not an `AreaChart`. For the line chart the prop is `breakLine={true}`. It will break if there's `null` of `NaN`.

**Comment by sartaj10** [comment]
Useful information - 
https://github.com/d3/d3-shape/blob/master/README.md#area_defined
https://bl.ocks.org/mbostock/3035090

**Comment by sartaj10** [comment]
PR #247 adds this feature
