### ISSUE TITLE
Legend - Remove Bottom Margin

### ISSUE THREAD

**Issue by luke-unifymonitor** [esnet/react-timeseries-charts#243]
Hi,

May I suggest that the default bottom margin placed on the Legend is removed?

If I required, I can easily add a bottom margin buy wrapping a div around it, but can't see how I can remove it without getting involved in the CSS.

Apologies if this is already an option.

Many thanks,

Luke.

**Comment by pjm17971** [comment]
Thanks for raising this. I think that's a good idea, it will just change people's layout, including ours. I think I will try to put this in at least as an option in the next release.

**Comment by luke-unifymonitor** [comment]
I see that the margins are applied here...

https://github.com/esnet/react-timeseries-charts/blob/master/src/components/Legend.js#L381
https://github.com/esnet/react-timeseries-charts/blob/master/src/components/Legend.js#L387

Maybe add margins to the defaultStyle ...

https://github.com/esnet/react-timeseries-charts/blob/master/src/components/Legend.js#L19

With defaults as they are now (20px).  Then going forward developers can change/remove the margins but your current layouts remain the same.

**Comment by luke-unifymonitor** [comment]
Let me know what you think of my suggestions above.  If you see no problems I'll make the change.

**Comment by sartaj10** [comment]
@luke-unifymonitor 
I've added a `marginBottom` prop to the Legend component now. This would allow more flexibility for other developers. Should be available in the next release
