### ISSUE TITLE
YAxis - showGrid

### ISSUE THREAD

**Issue by luke-unifymonitor** [esnet/react-timeseries-charts#244]
Would it be possible to add a showGrid={true/false} property to YAxis which would extend the ticks across the whole width of the chart?

**Comment by pjm17971** [comment]
This would be good, but I'm not sure how to resolve the fact that there's sometimes multiple YAxis. I wonder if a grid overlay would be the best approach. You'd reference an axis the way you would in a chart and it would render horizontal lines based on that axis scale. Then you could decide which axis to use or if to use multiple grid overlays. It's a little round about though.

**Comment by luke-unifymonitor** [comment]
I assumed that the ticks of the YAxis would get stretched across the width of the chart, and the showGrid property would allow us to control if that happens to a given YAxis or not.

```
<YAxis
   id="y1"
   showGrid={true}
   min={min}
   max={max}
   type="linear"/>

<YAxis
   id="y2"
   showGrid={false}
   min={min}
   max={max}
   type="linear"/>
```

**Comment by sartaj10** [comment]
Some useful links
- http://www.d3noob.org/2013/01/adding-grid-lines-to-d3js-graph.html
- https://bl.ocks.org/d3noob/c506ac45617cf9ed39337f99f8511218

**Comment by pjm17971** [comment]
<img width="903" alt="screen shot 2018-05-18 at 4 44 57 pm" src="https://user-images.githubusercontent.com/1288813/40267253-80054f14-5b0e-11e8-9d76-f274e02851dd.png">
