### ISSUE TITLE
setState is called in ChartRow after component unmounted

### ISSUE THREAD

**Issue by karolk** [esnet/react-timeseries-charts#246]
version: 0.14.0
React version: 16.3.2

When I first create a ChartContainer with a ChartRow component and pass a timeRange it works. After that if I pass an empty timeRange React shows an error: 

```
warning.js:33 Warning: Can't call setState (or forceUpdate) on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in ChartRow (created by TimeSeriesChart)
    in g (created by ChartContainer)
    in g (created by EventHandler)
    in EventHandler (created by ChartContainer)
    in g (created by ChartContainer)
    in svg (created by ChartContainer)
    in ChartContainer (created by TimeSeriesChart)
    in div (created by Resizable)
    in Resizable (created by TimeSeriesChart)
```

**Comment by daviddionys** [comment]
I wonder if you found any solution for this already.  I am using version 0.15.3 with react 16.4.2, and have a similar issue.  We have a plot with a rescaling y axis, and if the plot gets updated in the normal way, the y axis range values always are one step behind (the range update for the previous series).  

I solved this by removing the whole Rezisable/ChartContainer/ChartRow complex and then rendering it again, which works like a charm.  It does however trigger the exact same error as Karolk described in April, which is worrying as the memory leak might eventually lead to instable conditions.

**Comment by karolk** [comment]
@daviddionys eventually I didn't end up using this library but see if this may be related to hot module reloading. Try disabling it and see if this problem still happens.

**Comment by moxious** [comment]
I'm running into this too and spent a lot of time trying to chase around in my code why it might be happening.   This is against 0.15.5, and the relevant bits of the stacktrace are here:

```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in ChartRow (at CypherTimeseries.js:370)
    in g (created by ChartContainer)
    in g (created by EventHandler)
    in EventHandler (created by ChartContainer)
    in g (created by ChartContainer)
    in svg (created by ChartContainer)
    in ChartContainer (at CypherTimeseries.js:361)
    in div (created by GridColumn)
    in GridColumn (at CypherTimeseries.js:360)
    in div (created by GridRow)
```
