### ISSUE TITLE
react-hot-loader is included as dev dependency but used in library code

### ISSUE THREAD

**Issue by ethanroday** [esnet/react-timeseries-charts#271]
The `react-hot-loader` package is listed as a dev dependency in `package.json`, but it's `require`d in `lib/components/ChartContainer.js` and `lib/components/ChartRow.js`. Based on the discussion in #233, it should be fine to include it as a normal dependency.

**Comment by sartaj10** [comment]
Fixed in `v0.15.2`. Thanks for letting us know!
