### ISSUE TITLE
Wrong order for testing `this.props.style` using `_.isObject` or `_.isFunction`

### ISSUE THREAD

**Issue by ghm-tutela** [esnet/react-timeseries-charts#277]
Hello,

I was trying to style legend labels on some charts via the Styler and realized the `labelStyle` block in styler.js is hardcoded so it seems it cannot be used for styling labels. That's okay, because Legend.js says the passed style prop can be either a Styler, an object, or a function:

https://github.com/esnet/react-timeseries-charts/blame/master/src/components/Legend.js#L272

However, a few lines later the way that resolves uses `_.isObject` and `_.isFunction`:

```js
if (this.props.style instanceof Styler) {
  style = this.props.style.legendStyle(category.key, type);
} else if (_.isObject(this.props.style)) {
  style = this.props.style[category.key];
} else if (_.isFunction(this.props.style)) {
  style = this.props.style(category.key);
}
```

The definition of `_.isObject` is: (https://github.com/jashkenas/underscore/blob/master/underscore.js#L1319)

```js
// Is a given variable an object?
_.isObject = function(obj) {
  var type = typeof obj;
  return type === 'function' || type === 'object' && !!obj;
};
```

So any function passed into the style prop is treated as an object and then style is undefined and the function isn't called.

This is a common mix up it seems: https://github.com/jashkenas/underscore/issues/580 and, while I don't use or know underscore myself, I think changing the order should be enough to fix it.

This code seems to have been around for a few years. I git blamed it back to here:

https://github.com/esnet/react-timeseries-charts/commit/d5f76e6f4b5caf833165284180d1fbc02f7cd415#diff-dd85333000115763b2c2e8b3cbea9bdaR270

Which shows it's also used outside of just the Legend component. I'm surprised no one else has raised an issue about this? I wonder if I'm missing something, let me know.

Thanks for making the library, it's been very useful.

**Comment by sartaj10** [comment]
Hi @ghm-tutela 
Thanks for raising this issue. A re-arrangement of the order would solve this. We usually use the Styler to style charts and didn't notice this.
It should be fixed in the next release

**Comment by sartaj10** [comment]
Fixed in https://github.com/esnet/react-timeseries-charts/commit/8a76f8516199b031377358070fe590c9564fcb39
