### ISSUE TITLE
trackerShowTime ignored by ChartContainer

### ISSUE THREAD

**Issue by ikassi** [esnet/react-timeseries-charts#286]
Hi there,

I am trying to reset the `trackerShowTime` attribute on ChartRow but it's being reset by ChartContainer https://github.com/esnet/react-timeseries-charts/blob/fed7ede5db2edea5e4dfa6d6329fccc9836f82f7/src/components/ChartContainer.js#L286
What's the purpose of this choice and how can I get around this?

**Comment by pjm17971** [comment]
Yes, the tracker is controlled from the top of the render (at the ChartContainer level) as it extends over multiple rows. The time is just shown at the top of the first row, while it's possible to just show the info box part on the row being hovered over. That's why it does that.

**Comment by jonas-arkulpa** [comment]
@pjm17971 This sounds like a good default, but this way the documented trackerShowTime prop of the ChartRow always gets overwritten. There is no ability to hide the time.

The following example implies that you could pass that prop to the container, which is not the case:
https://github.com/esnet/react-timeseries-charts/blob/12ab1e7c025f404662c0697b53b4e371fb8c0570/src/website/packages/charts/examples/cycling/Index.js#L526

I have also no ability to style the time to make it somewhat visible in our case.
![image](https://user-images.githubusercontent.com/17269256/46728600-76294b80-cc83-11e8-86fc-471d14ef30c0.png)
https://github.com/esnet/react-timeseries-charts/blob/12ab1e7c025f404662c0697b53b4e371fb8c0570/lib/components/TimeMarker.js#L134
Why is this not a prop like infoStyle?

**Comment by jonas-arkulpa** [comment]
For future reference:
I worked around this issue with adjusting the colors.
Darken the text color with a wrapping css class like:
`svg {
    text {
      fill: black !important;
    }
  }`
And made the line lighter.
![image](https://user-images.githubusercontent.com/17269256/46742172-c8c82f00-cca6-11e8-8980-c597139e36f2.png)

**Comment by bminer** [comment]
Just ran into this bug also.  This issue should be re-opened.  The ChartContainer is overriding the prop passed to the ChartRow component.

@jonas-arkulpa - Thanks for the workaround

**Comment by bminer** [comment]
Another workaround is to add an empty `<ChartRow>` to the `<ChartContainer>`.

```jsx
<ChartRow height="0">
	<Charts />
</ChartRow>
```

**Comment by joshuaball** [comment]
Ran into this bug also.  Please reopen the issue.
