### ISSUE TITLE
BarChart minBarHeight at 0 can still be highlighted

### ISSUE THREAD

**Issue by brenkao** [esnet/react-timeseries-charts#294]
### Background
I am trying to make a stacked bar chart where some values are 0.  I don't expect these values to show up on the final chart.
### Problem
Even when the value is 0, I can still highlight the pixel for the 0 value.
### Cause
Rectangle is created even when the height is set to 0.  This is regardless of minBarHeight={0}.
### Possible Solution
Modify BarChart.js to not create a rectangle when height is 0
```javascript
// Allow negative values. Minimum bar height = 1 pixel.
// Stack negative bars below X-axis and positive above X-Axis
var positiveBar = height >= 0;
height = Math.max(Math.abs(height), minBarHeight);
var y = positiveBar ? yposPositive - height : yposNegative;
if(height == 0) return;
```

**Comment by pjm17971** [comment]
I've pondered this for a while, and I guess I don't understand what you mean by "I can still highlight the pixel for the 0 value". Can you explain further?

**Comment by brenkao** [comment]
![screenshot from 2018-08-07 16-30-12](https://user-images.githubusercontent.com/15950811/43807917-61591baa-9a5f-11e8-9e95-1966fca072f1.png)
This screenshot shows that a rectangle gets created even though the height is 0.

![screenshot from 2018-08-07 16-30-43](https://user-images.githubusercontent.com/15950811/43807920-69461552-9a5f-11e8-9b7b-5afb0474b3a5.png)
I can still hover this rectangle and see 0.
I expect that the 0 rect height to not be hover-able.
Does this clarify the issue?

**Comment by sartaj10** [comment]
This issue is solved and it would be in the next release! Thanks for raising the issue
