### ISSUE TITLE
Clicking on the chart doesn't provide information about where was clicked

### ISSUE THREAD

**Issue by iabw** [esnet/react-timeseries-charts#296]
Nothing is passed through [the EventHandler's click](https://github.com/esnet/react-timeseries-charts/blob/431290152ffc710b1affd86acce1f77f425cb0d2/src/components/EventHandler.js#L178) or [the ChartContainer's click](https://github.com/esnet/react-timeseries-charts/blob/38cd7231db04c2a474fc9769256cf590145aa08a/src/components/ChartContainer.js#L103).

My use-case is to control an element separate from the chart, passing it the time that was clicked.

You could keep the current mouse state via mousemove or tracker callbacks to use when a click happens, but probably it'd be preferable to just send the x/y and/or time/value through the click handlers.

**Comment by sartaj10** [comment]
Thanks for the PR and raising this issue!
