### ISSUE TITLE
Should be able to disable scroll wheel zoom behavior

### ISSUE THREAD

**Issue by iabw** [esnet/react-timeseries-charts#297]
Coming off [the discussion](https://github.com/esnet/react-timeseries-charts/pull/252#discussion_r202898021) on PR #252, it seems like it would be worth adding a new prop: `enableWheelZoom`. I think it would only need to be checked at the [beginning of handleScrollWheel](https://github.com/esnet/react-timeseries-charts/blob/master/src/components/EventHandler.js#L58).

Since this separates the scrollwheel zoom from panning behavior, `enablePanZoom` should probably be renamed to `enablePanDrag` (or something similar). We can leave `enablePanZoom` as a prop that turns on both scrollwheel and panning behaviors (which would be individually toggled by `enablePanDrag` and `enableWheelZoom`) so this wouldn't be a breaking change for the classic pan zoom behavior.

**Comment by sartaj10** [comment]
Continuing the discussion in #303 
Closing this.
