### ISSUE TITLE
default tracker not provided with infoStyle prop

### ISSUE THREAD

**Issue by iabw** [esnet/react-timeseries-charts#304]
TimeMarker takes an infoStyle prop to apply custom styles, but that prop isn't passed into the default tracker from ChartContainer - https://github.com/esnet/react-timeseries-charts/blob/6cd9828aac1baa561a565986b89c5b5bca57da24/src/components/ChartContainer.js#L320

It'd be nice to be able to style the default tracker instead of having to manage a custom TimeMarker if you want anything other than a 1px grey line.

Maybe even allowing passing a React component that would over-ride TimeMarker if it exists, accepting the same props.

**Comment by sartaj10** [comment]
Thanks for raising this, I've added the feature to style the tracker. Will be available in the upcoming release
