### ISSUE TITLE
ChartRow not showing

### ISSUE THREAD

**Issue by msansoni** [esnet/react-timeseries-charts#305]
<img width="644" alt="demo" src="https://user-images.githubusercontent.com/15960212/44007255-f3e06ffe-9e89-11e8-9bd3-b315418d6b0b.png">
Trying the baseline demo it seems the ChartContainer renders fine, however the ChartRow containing YAxis and simple LineChart does not render so the SVG height is only 63 pixels (28 for the title and 35 for the X axis and ticks). Is there some CSS/styling that I need to define to show the ChartRow? - Apologies this isn't an issue as it's a user error I'm sure, - just can't find a forum to ask this kind of n00b question.

```render() {
    return (
          <Resizable>
              <ChartContainer width={800}
                  title="Euro price (USD)"
                  titleStyle={{ fill: "#555", fontWeight: 500 }}
                  timeRange={series.range()}
                  format="%b '%y"
                  timeAxisTickCount={5}
              >
                  <ChartRow height="250">
                      <YAxis
                          id="price"
                          label="Price ($)"
                          min={series.min()}
                          max={series.max()}
                          width="60"
                          format="$,.2f"
                      />
                      <Charts>
                          <LineChart axis="price" series={series} style={style} />
                          <Baseline
                              axis="price"
                              style={baselineStyleLite}
                              value={series.max()}
                              label="Max"
                              position="right"
                          />
                          <Baseline
                              axis="price"
                              style={baselineStyleLite}
                              value={series.min()}
                              label="Min"
                              position="right"
                          />
                          <Baseline
                              axis="price"
                              style={baselineStyleExtraLite}
                              value={series.avg() - series.stdev()}
                          />
                          <Baseline
                              axis="price"
                              style={baselineStyleExtraLite}
                              value={series.avg() + series.stdev()}
                          />
                          <Baseline
                              axis="price"
                              style={baselineStyle}
                              value={series.avg()}
                              label="Avg"
                              position="right"
                          />
                      </Charts>
                  </ChartRow>
              </ChartContainer>
          </Resizable>
    );
  }```

**Comment by sartaj10** [comment]
@msansoni 
Hey, hopefully this helps you. I've recreated the baseline example we have on the charts website.
https://codesandbox.io/s/l28vmvp2n9

**Comment by sartaj10** [comment]
Another question, were you receiving any errors as well? Also, what browser/environment are you using? We recommend using Chrome / Firefox

**Comment by msansoni** [comment]
Hey @sartaj10  thanks for your response.

I'm building an electron app, so it's chromium.
Interestingly I've directly copied your code and experience the same issues in dev. However when packaged it renders correctly. So I'm just going through all the hot-loader scripts and removing differences between the boilerplate in dev and packaged to find out what is causing it.

Will update once I've found the cause!

**Comment by msansoni** [comment]
Digging further...

For info, I'm using this boilerplate: [electron-react-boilerplate](https://github.com/chentsulin/electron-react-boilerplate).

When in development it uses a different renderer js file, it differentiates between the two in the [app.html](https://github.com/chentsulin/electron-react-boilerplate/blob/master/app/app.html). Forcing it to run the prod renderer the ChartRow renders correctly.

The differences between dev and prod look to be mainly for hot loading etc., however I've made your demo use hot-reload and that doesn't recreate the issue, and at the moment I can't seem to force yarn to run the dev environment with HMR off. 

At the moment I can get around it by running the standard yarn/npm start rather than in dev with hot-reload and will keep looking to find the root cause, but it's probably worth closing this in the meantime, and I'll be on the lookout if anyone post a similar issue/question here in the future to point them in this direction.

**Comment by pjm17971** [comment]
Possibly related: #233
This was resolved, but it may well be a similar issue.

**Comment by msansoni** [comment]
@pjm17971 does look to be related, but I'm using v0.15.2, so should have that specific fix. Need to disable HMR in my code, but that's currently an open issue on the other code base.

**Comment by ethanroday** [comment]
I'm seeing this as well on v0.15.5 from a regular, non-Electron Webpack config. If I disable HMR the problem goes away. Other version info:
React: 16.6.3
React HMR: 4.3.12
Webpack: 4.20.2
