### ISSUE TITLE
Tracker should support displaying points and labels

### ISSUE THREAD

**Issue by pjm17971** [esnet/react-timeseries-charts#31]
While the tracker works well for indicating the currently hovered time, it would be nice if you could mark points on the data as well. Perhaps it should support showing the line, showing a list of points, and/or showing a list of points and labels. The calling code would be responsible for deciding what to show, what points to add, what labels to apply etc. It could also snap the marker to the data is necessary.

We could pass all this in as props on the ChartRow.

**Comment by pjm17971** [comment]
Another option is something like this:

<img width="325" alt="screen shot 2016-02-12 at 10 08 09 am" src="https://cloud.githubusercontent.com/assets/1288813/13015907/9ae0e232-d170-11e5-8bff-6c18800719a2.png">

You'd give the tracker a callback function as a prop. That function would be called with the timestamp of the hovered position. You'd return a set of key value pairs and it would display them as above.

**Comment by gfoiani** [comment]
This solution would be optimal. Some possible improvements could be the addition of color of the series next to the labels and the possibility to customize the timestamp format.

**Comment by gfoiani** [comment]
Have you already planned when this feature will be released?

Thanks

**Comment by pjm17971** [comment]
Sorry, it is not in my current plans. Generally we display the value outside of the chart itself, so there's no internal driver. PRs are welcome of course.

**Comment by pjm17971** [comment]
An initial implementation of this for use with LineCharts or AreaCharts looks like this:

![tracker-tooltip](https://cloud.githubusercontent.com/assets/1288813/15129011/02d6abc0-15f4-11e6-9f0b-a6bea21baa83.gif)

This is an extension to the general purpose tracker defined as props on the ChartContainer:

```
<ChartContainer
    timeRange={this.state.timerange}
    trackerPosition={this.state.tracker}
    onTrackerChanged={this.handleTrackerChanged}
    trackerValues={trackerValues}
    trackerHintHeight={50} ... />
```
trackerValues is a list of label, value pair. Its up to the user to decide what to add there.

**Comment by pjm17971** [comment]
An experimental implementation of tooltips for ScatterCharts is also in the works:

![scatter-tooltip](https://cloud.githubusercontent.com/assets/1288813/15129139/9cd1156c-15f4-11e6-958e-5b00d9dff7f2.gif)

**Comment by gfoiani** [comment]
Can you please provide an example of trackerValues format?
Can I use a callback function and fill this variable with chart points based on current tracker position?

**Comment by pjm17971** [comment]
This functionality is still only in the v0.9 branch, but here's an example:
https://github.com/esnet/react-timeseries-charts/blob/v0.9/examples/modules/channels.jsx#L310

We hope to merge this branch into master by the end of the month.

**Comment by gfoiani** [comment]
Ok thanks, I switched to v0.9 branch because I need this feature.
I can give you some feedbacks if you want.

**Comment by pjm17971** [comment]
This is now in master. It will be in the 0.9 release.
