### ISSUE TITLE
Remove flexbox-react dependency

### ISSUE THREAD

**Issue by jtiscione** [esnet/react-timeseries-charts#310]
In the legend there are a few elements with rudimentary CSS flex layout, and Legend.js uses components from flexbox-react to apply them. The dependency on flexbox-react causes problems:

- It's lugging around an old version (2.0.0) of styled-components. That adds 30K to the webpack bundle size, which is ridiculous for what it does. It has a bigger footprint than underscore.js (25K).
- Components from flexbox-react cause strange rendering problems if the app also renders components based on a newer version of styled-components- they don't always have their styles applied for some reason, probably because of a version conflict. (The latest styled-components version is 3.4.2).
- The flexbox-react module is used nowhere except Legend.js, which should be able to apply the simple flex styles manually anyway.

**Comment by pjm17971** [comment]
I was looking at this myself a few weeks ago. Thanks for raising this. Any chance you could submit a PR?

**Comment by jtiscione** [comment]
The trivial fix would be to pull in styled-components as a dependency and use that. That would be a major decision though and I'm assuming we don't want to introduce styled-components just for a legend. How does most of the code handle styling? With style attributes?

**Comment by jtiscione** [comment]
OK, I just submitted a PR. It only needed a few div tags with some flex style attributes, and it seems to be working fine. I also fixed the bullets (they were a little vertically off-center because the parent div's "align-items" property was defaulting to "flex-start" instead of "center"). So the build should be 20K lighter now.

**Comment by pjm17971** [comment]
Awesome! I’ll take a look this week.
