### ISSUE TITLE
bug: reactHotLoadder.areComponentsEqual is not a function

### ISSUE THREAD

**Issue by uclanate** [esnet/react-timeseries-charts#312]
Hi,

I'm trying to use react-timeseries-charts in a React project (React ^16.2.0 , Gatsby ^1.9.158) and getting the following error. Let me know if more details are needed to replicate this error!

Thanks,
Nate

TypeError: (0 , _reactHotLoader.areComponentsEqual) is not a function
(anonymous function)
node_modules/react-timeseries-charts/lib/components/ChartContainer.js:291
  288 | 
  289 | _react2.default.Children.forEach(this.props.children, function(childRow) {
  290 |     if (
> 291 |         (0, _reactHotLoader.areComponentsEqual)(childRow.type, _ChartRow2.default)
  292 |     ) {
  293 |         //
  294 |         // Within this row, count the number of columns that will be

**Comment by sartaj10** [comment]
Hi,
Thanks for raising this issue. 
I believe this seems to be an issue with Gatsby and not this library...
Are you using V1.9.277 for gatsby?

https://github.com/gatsbyjs/gatsby/pull/4500
https://github.com/gatsbyjs/gatsby/issues/7209
