### ISSUE TITLE
check published npm registry 

### ISSUE THREAD

**Issue by KinTsang** [esnet/react-timeseries-charts#319]
Hi,

In my project's package.json I initially had `"react-timeseries-charts": "^0.11.4"` which should translate to the most recent version of 0.15.3. However, it seems like it is still not retrieving what is in the current master branch since it was also installing the dependency `flexbox-react` during npm install.

I had to update my package.json to point directly at the current master branch to prevent it from installing `flexbox-react` ("react-timeseries-charts": "https://github.com/esnet/react-timeseries-charts.git#master")

Thanks,
Kin

**Comment by sartaj10** [comment]
Hi @KinTsang 
The version without `flexbox-react` (v0.15.4) has still not been released and published to npm.
It'll be done by next week

Thanks!
