### ISSUE TITLE
Can the tracker line be styled

### ISSUE THREAD

**Issue by daviddionys** [esnet/react-timeseries-charts#321]
Dear, I want to insert a vertical line in the chart at the time that is selected, as in 
```
<ChartContainer
                  timeRange={series.range()}
                  showGrid={false}
                  showGridPosition="under"
                  timeAxisTickCount={5}
                  trackerPosition={this.state.currentDateTime}
>
```
This works great, the line has the exact position.  However, there seems to be no way to style this line.
In EventMarker, stemStyle can be passed, e.g. `{ {stroke: "rgb(255,153,153)", strokeWidth:"5px",cursor: "crosshair", pointerEvents: "none" }}` but then I need to pass an infobox (which I do not want to do), and I had problems with the offsetY for the marker there as well.  

Can a custom style be applied in any way to the tracker generated directly from the ChartContainer?

**Comment by sartaj10** [comment]
@daviddionys 
Hi, thanks for the question.
Yes, you can apply a `trackerStyle` and pass it to the ChartContainer as shown below:
https://github.com/esnet/react-timeseries-charts/blob/master/src/components/ChartContainer.js#L629

This is also shown in the traffic example
https://github.com/esnet/react-timeseries-charts/blob/74e051d097b732bd492349c8e567d9917e2492bc/src/website/packages/charts/examples/traffic/Index.js#L56

**Comment by daviddionys** [comment]
Dear Sartaj, this worked indeed, thank you so much, you really made my day!  

I should probaby check the components directly in github, because I was checking the API at https://software.es.net/react-timeseries-charts/#/api/charts/ChartContainer

**Comment by sartaj10** [comment]
Hmm, I guess we forgot to update the docs. Thanks, but that website is usually up to date with all the props.
