### ISSUE TITLE
[Box Chart] changing rollup values

### ISSUE THREAD

**Issue by gilneto8** [esnet/react-timeseries-charts#325]
I'm receiving a couple of values in the following format:
`data: { time: [<date>], min: [<number>], max: [<number>], options: [{...}] 
}`

Basically, to show up a chart with these values I have to go through each of these structures indexes (they all match, even if some are 'null'), no problem there. As you can see, since we have a minimum and a maximum values for each timeframe, our backend is already taking care of some rollup logic: it creates an 'abstraction', so we always have the same amount of timeframes, with different values associated with each of them.

The problem here is that sometimes these values come in intervals of minutes, or even seconds. And so, I would like to show these values on their correct timeframes on the chart, and I can't seem to seem to work with the rollup options on the chart configuration. This is my code right now, with no rollup configuration tests:

```
            <ChartContainer
                timeRange={this.state.timerange}
                enablePanZoom={true}
                onBackgroundClick={() => this.setState({ selection: null })}
                onTimeRangeChanged={this.handleTimeRangeChange}
            >
                <ChartRow height="300">
                    <Charts>
                        <BoxChart
                            axis={`${this.state.name}_axis`}
                            style={style}
                            column={`${this.state.name}`} 
                            series={this.state.series[0]}
                            info={this.infoValues()}
                            infoWidth={200}
                            infoHeight={75}
                            highlighted={this.state.highlight}
                            onHighlightChange={highlight =>
                                this.setState({ highlight })
                            }
                            selected={this.state.selection}
                            onSelectionChange={selection =>
                                this.setState({ selection })
                            }
                        />
                    </Charts>
                    <YAxis
                        id={`${this.state.name}_axis`}
                        label="Temperature"
                        min={-5}
                        max={50}
                        width="70"
                        format={n => Number(n).toFixed() + "°C"}
                    />
                </ChartRow>
            </ChartContainer>
```

As this is, I can see the information gathered for each day separately, and for the case I exposed above, this is not ideal. 
Any help would be great.

Thanks,
Gil

**Comment by sartaj10** [comment]
Were you able to fix this? @gilneto8

**Comment by gilneto8** [comment]
@sartaj10 no, I wasn't. We opted for the line charts for now.
