### ISSUE TITLE
Add band charts

### ISSUE THREAD

**Issue by gilneto8** [esnet/react-timeseries-charts#328]
I have a chart container with 3 Line Charts plotted, one for the maximum values coming from an API, one for the minimum and one for their average.
For visualization purposes only, I'd like to fill the area in between the minimum and maximum lines in a semi-transparent color. Is this achievable? Couldn't find any reference/example for this anywhere.

Thanks,
Gil

**Comment by pjm17971** [comment]
There's band chart code integrated with the incomplete Typescript port of this code. That would do what you want, but unfortunately isn't available in the released library. So currently this isn't possible. But I'll add a request to move that code internally to Jira for possible inclusion down the road.

**Comment by gilnetoglartek** [comment]
Thanks for the quick answer, looking forward for that update.

**Comment by gilneto8** [comment]
Thanks for the quick answer. Looking forward for that update.

**Comment by wtesler** [comment]
@sartaj10 Does the BandChart need to be exported in `entry.js` still? It doesn't appear to be externally available.

**Comment by sartaj10** [comment]
@wtesler 
Yes, thanks for raising this. It does need to be exported, I'll fix that

**Comment by sartaj10** [comment]
@wtesler 
Fixed in v0.15.5

**Comment by wtesler** [comment]
Awesome
