### ISSUE TITLE
Resizable doesn't properly bind to 'this'

### ISSUE THREAD

**Issue by albertcarrete** [esnet/react-timeseries-charts#329]
The Resizable component is not dynamically resizing charts in my tests with React 16.3.0 and 16.4.0. Upon examining the Resizable component, the `handleResize()` method doesn't seem to be returning a value for `this.container` and is therefore not updating the width. I think the change from #282 that prevented a memory leak also disconnected the 'this' reference needed for `handleResize()` to properly function. I found that changing the constructor from 
```
export default class Resizable extends React.Component {
    constructor(props) {
        super(props);
        this.state = { width: 0 };
    }
```
to

```
export default class Resizable extends React.Component {
    constructor(props) {
        super(props);
        this.state = { width: 0 };
        this.handleResize = this.handleResize.bind(this);
    }
```
ensured that `this` is accessible inside the handleResize method. 

Note: I have a PR ready to launch if you feel this is the best fix.

**Comment by sartaj10** [comment]
@albertcarrete 
Yes, this makes sense. Please send a PR and I'll merge that!
Thanks
