### ISSUE TITLE
Relative time axis scales

### ISSUE THREAD

**Issue by pjm17971** [esnet/react-timeseries-charts#33]
Sometime you want to display a time axis starting at 0, rather than one over a specific time range. For example you might display data from a test. It doesn't matter that the test was on Wednesday at 8am. You want to beginning of the test data to be labeled 0 and then have useful time increments from there, like 0:15, 0:30, 0:45, 1hr, 1:15 ...

**Comment by gfoiani** [comment]
How can I display X axis starting from 0?
I set the `format="relative"` property on ChartContainer but X Axis starts from something like `16940d 16:33`.
How can I fix?

**Comment by pjm17971** [comment]
I think you need the timestamps to also start from 0.

**Comment by gfoiani** [comment]
ok thanks
