### ISSUE TITLE
Stale version still published on npm?

### ISSUE THREAD

**Issue by jtiscione** [esnet/react-timeseries-charts#331]
I submitted a PR to [remove the flexbox-react dependency](https://github.com/esnet/react-timeseries-charts/issues/310) which was merged on August 30 I think. I didn't presume to bump the project version number in package.json and left it at 0.15.3. (I figured whoever did the npm publish would want to handle that.)

According to npm the module did get published about a week after that PR merge, either by a human or a machine. But since nobody's changed the version number in package.json, they ignored it.

I didn't realize it until this morning when I stumbled flexbox-react still hiding in node_modules. Was the plan to have 0.15.4 published at this point or did I goof by not changing the 3 to a 4 myself? The comments on [another issue](https://github.com/esnet/react-timeseries-charts/issues/319) imply that 0.15.4 should be available by now.

**Comment by pjm17971** [comment]
We haven't pushed a new version since there's generally been a lack of activity on this library in the past month or so. We were hoping to get to some of the issues that have been accumulating but no luck. Hopefully soon.
