### ISSUE TITLE
Periods in column name doesn't render chart

### ISSUE THREAD

**Issue by brenkao** [esnet/react-timeseries-charts#332]
Hi,
If I have for example google.com as a column name in my LineChart, the Line does not render but if the column name is google com without the "." then the chart renders fine.
````javascript
const series = new TimeSeries({
                    name: "test",
                    columns: ["google.com"],
                    points: this.buildpoints(data)
                })
````

Example - https://codesandbox.io/s/ykj049y79j

**Comment by sartaj10** [comment]
This illustrates the issue - https://codesandbox.io/s/ykj049y79j

**Comment by pjm17971** [comment]
Periods in Pond represent a path to deep data, so you can't do that. Sorry, that's pretty low level to how it works.
