### ISSUE TITLE
Values style in YAxis is applied to <g> that contains label

### ISSUE THREAD

**Issue by NicholasGWK** [esnet/react-timeseries-charts#333]
Hey, I think I may have found a bug but not sure. I'm trying to display a YAxis without ticks/values, and only a label (which is a bad chart, but still, it matches the design :P ). I couldn't seem to get it to work with tickCount = 0, so I decided to use styles. However in the DOM in appears if I hide the values, it also affects the label.

Style on YAxis:

```
style={
  {
    ticks: { display: 'none' },
    values: { visibility: 'hidden' },
    label: { display: 'block', stroke: 'red' },
  }
}
```

Produces the following DOM, which hides the values AND the label:

<img width="767" alt="screen shot 2018-10-15 at 4 50 29 pm" src="https://user-images.githubusercontent.com/6642497/46977574-86ce2d00-d09a-11e8-90f6-a957a9ee3ea0.png">

Removing the hidden prop on values return the intended result:

![screen shot 2018-10-15 at 4 52 06 pm](https://user-images.githubusercontent.com/6642497/46977636-b1b88100-d09a-11e8-97a6-db2ebf5d2a42.png)

**Comment by NicholasGWK** [comment]
Seems to work fine if I use `stroke: none` and `fill: none` so I guess I'm just bad at SVG + CSS 😂 . Can probably close!

**Comment by pjm17971** [comment]
Ok, we'll close it. That's kind of an outlier request. Good luck with that :)
