### ISSUE TITLE
Scatter chart bad point check does not check typeof 'undefined'

### ISSUE THREAD

**Issue by renhax** [esnet/react-timeseries-charts#339]
As in here, https://github.com/esnet/react-timeseries-charts/blob/master/src/components/ScatterChart.js#L213. It only checks value null and N/A, but doesn't do anything if input value is undefined, what's the reason behind this?

**Comment by sartaj10** [comment]
@renhax 
A check for undefined can also be added to the above

**Comment by sartaj10** [comment]
Added in v0.15.5
