### ISSUE TITLE
Website caching issue?

### ISSUE THREAD

**Issue by ethanroday** [esnet/react-timeseries-charts#347]
When I go to https://software.es.net/react-timeseries-charts/ in my browser, I see no content and the following console errors:
![image](https://user-images.githubusercontent.com/896670/49692049-1a553480-fb05-11e8-9c0c-2e21b921d62c.png)
I'm guessing this is some sort of caching issue, since it works fine when I open it in an incognito window.

**Comment by sartaj10** [comment]
@ethanroday 
Do you still see this? I can't seem to reproduce this in my browser

**Comment by ethanroday** [comment]
I had the issue only intermittently in the first place. If there's no repro then I'm happy to just close.
