### ISSUE TITLE
How to increase wheel scroll zoom in speed?

### ISSUE THREAD

**Issue by renhax** [esnet/react-timeseries-charts#349]
Hi,
I'm trying to use scroll wheel zoom in for my LineChart, but I noticed every time I scroll the mouse wheel, the x-axis only change a little. Is there anyway to make the zoom in faster?

Thanks,
Renhao

**Comment by renhax** [comment]
Does each wheel scroll sticks to change a fix number of time range? I use a very wide time range, lasts more than 3 years. Is there any work around?

**Comment by root0x** [comment]
I've also got this issue. Is there actually any way to increase the mouse wheel zoom?
