### ISSUE TITLE
Some confusion around using TimeRangeEvent with a BoxChart

### ISSUE THREAD

**Issue by acomito** [esnet/react-timeseries-charts#354]
We're build some great charts for our IoT startup using this package-- it's the best chart package that I've seen for serious time-series charts. I'm having one issue recently that I wanted to post here.

**TLDR:**

I'm having some trouble getting TimeRangeEvent and BoxChart to work. Essentially, I need something similar to your NYC example here: http://software.es.net/react-timeseries-charts/#/example/nyc. 

I put together a reproduction with data similar to your NYC example. The only difference is I added timestamps to each datapoint: https://codesandbox.io/s/zq6kr2m2wx

When I run my current setup, I get `e.index is not a function`. It seems like the BoxChart is trying to call the IndexedEvent's index() method-- but the TimeRangeEvent doesn't have a index() method.

I'm thinking theres something simple missing, but I thought I'd create a ticket in case it's a bug. I'll keep looking and update this as I go.

**Extended Question:**

Right now I'm working on a BoxChart that (I think) requires the use of TimeRangeEvent. I see you have an example using some NYC here: http://software.es.net/react-timeseries-charts/#/example/nyc

That BoxChat example uses this data: https://github.com/esnet/react-timeseries-charts/blob/master/src/website/packages/charts/examples/nyc/knyc.json

We need to build virtally the same chart. The only difference is we want to use start/end timestamps (TimeRangeEvent) for each data point rather than an index/string (IndexedEvent). I'm basing this off the docs here:

```
The TimeSeries supplied to the boxplot, as the series prop can be one of two types:

It can be a TimeSeries containing IndexedEvents or TimeRangeEvents. In this case a column prop should be supplied to specify the data column containing the dimensions of the boxes. This props should be an array of size 1 to 5 elements. e.g. [12, 18, 22, 28]. The numbers should be ordered, lowest to greatest.

A TimeSeries containing timestamp based Events. In this case the boxplot will be aggregated for you. To control the aggregation you can supply an aggregation prop: a structure to specify the window size and reducers used to determine the boxes.

src: http://software.es.net/react-timeseries-charts/#/api/charts/BoxChart

```

reproduction: https://codesandbox.io/s/zq6kr2m2wx

**Comment by acomito** [comment]
**Update:**

We did get it working with the IndexedEvent but are having seeing some slight issues around the date math causing things to be off a little:

https://codesandbox.io/s/3y68r0om6q

**Comment by sartaj10** [comment]
Hmm, this seems to be an issue. I believe we are not handling that case here currently, as it can be seen from here :
https://github.com/esnet/react-timeseries-charts/blob/master/src/components/BoxChart.js#L94
https://github.com/esnet/react-timeseries-charts/blob/master/src/components/BoxChart.js#L440

There's also no method on the TimeRange to convert it to an index, which could have been a workaround for this..
https://esnet-pondjs.appspot.com/#/timerange

Thanks for raising this issue

**Comment by acomito** [comment]
Thanks for taking a look @sartaj10 I appreciate it.

Do you think adding an index method to the TimeRangeEvent in pondjs will solve this? 

We also weren't sure how the BoxChart would handle situations where the intervals differ (e.g. one may be 15 minutes, another 100 minutes-- as the examples we saw only use fixed/equal intervals like days).

**Comment by pjm17971** [comment]
@acomito Did you manage to resolve your issues? You can't really add a index() method to a timerange, indexes are a string that represents a specific unit of time, like a day 2018-09-11. They can be in local time or UTC (which might be related to your offset issue in the codesandbox above). A timerange event has a begin and end time, so it doesn't necessarily translate to an index, though it might. The box chart stuff is based on IndexEvents. I'm not sure if it would work on TimeRangeEvents but it probably could be adapted to work with them since and index does expose a begin and end time and that's all it needs (it might already work).

I'm going to close this for now, but if you'd like to discuss feel free to comment here.

**Comment by Skiv1989** [comment]
Was it solve some how? Regarding documentation: https://software.es.net/react-timeseries-charts/#/api/charts/BoxChart box chart series can be passed as IndexedEvents or TimeRangeEvents. But with timeRangeEvents I'm facing same problem as topic starter did. 
my pond js version is: 0.8.10
react-timeseries-charts is: 0.15.5
