### ISSUE TITLE
Brush examples

### ISSUE THREAD

**Issue by gfoiani** [esnet/react-timeseries-charts#36]
Hi all,

are there any examples that use the Brush feature?

Thanks

**Comment by pjm17971** [comment]
I have an example and a couple of associated bug fixes for the brushing functionality. I'll merge them in soon. Hopefully next week.

**Comment by pjm17971** [comment]
@gfoiani: I've updated the brushing code and added an example. The update is now on npm.

There's now a brushing example on the docs site:
http://software.es.net/react-timeseries-charts
That code is here:
https://github.com/esnet/react-timeseries-charts/blob/master/examples/modules/channels.jsx#L191

Hope this is helpful.

-Peter

**Comment by gfoiani** [comment]
Thanks @pjm17971 ,
I saw that the Brush component is not exported in the index.js file so, how can I import it in my project?

Thanks

**Comment by pjm17971** [comment]
@gfoiani: I pushed an updated version this morning that should export the brush component correctly. Sorry about that.

**Comment by gfoiani** [comment]
Thanks @pjm17971 now it works great!
