### ISSUE TITLE
Provide Spider/Radar Chart

### ISSUE THREAD

**Issue by wokier** [esnet/react-timeseries-charts#361]
**Is your feature request related to a problem? Please describe.**
I have a missing chart type

**Describe the solution you'd like**
Spider Chart type https://en.wikipedia.org/wiki/Radar_chart

**Describe alternatives you've considered**
Use another chart lib

**Comment by pjm17971** [comment]
That's an interesting suggestion, but is probably out of scope for this library at this point. I might be willing to accept a PR for it, but for now I'm closing.
