### ISSUE TITLE
Box Plot for financial time series?

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [esnet/react-timeseries-charts#384]
Could one theoretically use this to display ohlc candle data?
https://software.es.net/react-timeseries-charts/#/example/nyc

Is there a grouping feature which can aggregate box plots to 5m 10m timeframes and so on?

**Comment by sabman** [comment]
I think you need to use the aggregation functionality in Pond.js http://software.es.net/pond/#/aggregation

**Comment by smeijer** [comment]
An example incorporating this one, would be very lovely!

Think of a candle chart, with the timeframes using `aggregation`, and `green` and `red` bars.
