### ISSUE TITLE
Realtime: Cannot construct Event instances directly

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [esnet/react-timeseries-charts#389]
I follow the example page using pondjs to create a realtime chart
```

const stream = new Stream();

Pipeline()
    .from(stream)
    .to(EventOut, event => {
        // store the output events in our component state
    });

setInterval(()=>{
  const value = Math.round(Math.random()*100);
  const time = new Date();
  const event = new Event(time, value);
  stream.addEvent(event);
}, 1500);

```

**Comment by hp8wvvvgnj6asjm7** [comment]
Also your example page says: 

```const value = getRandomValue();
const time = getNextTime();
const event = new Event(t, value);
```

What is t? t does not exist.

**Comment by sartaj10** [comment]
@hp8wvvvgnj6asjm7 sorry, it's `time` instead of `t`

**Comment by hp8wvvvgnj6asjm7** [comment]
Thank you, but I really cant even instantiate new Event. . getting errors

**Comment by hp8wvvvgnj6asjm7** [comment]
Cannot construct Event instances directly

**Comment by hp8wvvvgnj6asjm7** [comment]
Using webpack, maybe an issue with it?

**Comment by sartaj10** [comment]
hmm, we've had a few people have issues with webpack in the past but I believe we fixed that. Here's one of the issues - https://github.com/esnet/react-timeseries-charts/issues/233

**Comment by hp8wvvvgnj6asjm7** [comment]
No my charts are rendering correctly. I just can't use " new Event "

**Comment by hp8wvvvgnj6asjm7** [comment]
import { TimeSeries, Pipeline, Stream, EventOut, Event  } from "pondjs";

**Comment by sartaj10** [comment]
I'm not being able to recreate the issue. Here's a working example - 
https://codesandbox.io/s/8nnm2kzl20

Maybe, see what versions of pondjs are you using?

**Comment by hp8wvvvgnj6asjm7** [comment]
The non typescript version, which should be compatible with react-timeseries-charts

Your examples are written in a very confusing manner, they say I have to create a new Event( ) 
but actually i need to choose from another event type inside pondjs.

I already had the suspicion that there was something odd with it.

**Comment by hp8wvvvgnj6asjm7** [comment]
Events

To do this, each event is generated semi-randomly, but they could be coming from a real source. We add a new Event for each minute, but emit 5 per second to speed up the simulation. Essentially we do this:

import { Event } from "pondjs";

const value = getRandomValue();
const time = getNextTime();
> const event = new Event(t, value); 
This is declared very literally, like I would have to write it down exactly like that.

**Comment by hp8wvvvgnj6asjm7** [comment]
Thanks for clearing this up.
