### ISSUE TITLE
Schedule for the next release?

### ISSUE THREAD

**Issue by kephin** [esnet/react-timeseries-charts#396]
# ❔Question

Just wondering do you have schedule for the next release? Thanks a lot! 😃

There are some new features and bug fixes in master but couldn't install through npm. If you don't have the schedule for it, is there a suggested way to take the feature/fix we want in our code base? Thanks!

Just to reference the feature/fix we need 😅
1. Scrolling issue in ChartContainer https://github.com/esnet/react-timeseries-charts/issues/375
2. configure chart row axis margin https://github.com/esnet/react-timeseries-charts/issues/341

Thanks for your help!

**Comment by pjm17971** [comment]
I'm hoping to do it this week. We need #375 too.

**Comment by kephin** [comment]
Thanks for your help!
