### ISSUE TITLE
Warning: Received NaN for the `height` attribute

### ISSUE THREAD

**Issue by peterbe** [esnet/react-timeseries-charts#399]
# 🐛Bug report

**Describe the bug**
Trying to make a simple bar chart with two columns and I keep getting this warning:

```
Warning: Received NaN for the `height` attribute. If this is expected, cast the value to a string.
```

But it appears to be working. 

**To Reproduce**

https://codesandbox.io/s/goofy-napier-rx6v7

**Expected behavior**
No warnings.

**Screenshots**
<img width="1482" alt="Screen Shot 2019-05-31 at 8 07 20 AM" src="https://user-images.githubusercontent.com/26739/58705194-75f9cf80-837c-11e9-8abf-6b09298d94ec.png">

**Desktop (please complete the following information):**
 - Firefox but I don't think it's applicable

**Smartphone (please complete the following information):**
n/a

**Additional context**
It works but the warning is annoying.

**Comment by peterbe** [comment]
Hm. Perhaps I just don't know how to use `<BarChart>` stacked or side-by-side. 
If I change it to:
```
columns={["created"]}
```
instead of 
```
columns={["created", "processed"]}
```
[Then it doesn't throw the warning](https://codesandbox.io/s/reacttimeserieschart-warning-elyt5?fontsize=14)

**Comment by pbatleyGH** [comment]
Try changing it to this?

```
points: data.map(([d, ...value]) => [
  Index.getIndexString("1h", new Date(d)),
    ...value
  ])
```

Using the spread operator means you'll pass two data columns in to match the number of columns you're declaring that the TimeSeries has.

**Comment by peterbe** [comment]
[Thank you!](https://codesandbox.io/s/react-timeseries-chart-warning-t286p)
