### ISSUE TITLE
Question: Can this lib be used to create a timeline of events?

### ISSUE THREAD

**Issue by TroyLDay** [esnet/react-timeseries-charts#41]
This looks like a very nice library and if there are any examples showing usage as a events timeline, I'd be very interested to see. Kind Thanks!

**Comment by pjm17971** [comment]
Unfortunately there's no real support for showing an events timeline. We've done some experiments in the past but nothing that is likely to help you. I'll add an issue for creating this, as it's something I'd like to support. It's a logical extension to what the library can do right now.

Were you thinking something like this:
github.com/yuanyan/react-timesheet
?

BTW, it is possible to make your own charts. If you look at one of the simple existing charts, like the BarChart, you'll see how they work. When rendered they will have several props passed in: the size of the area they should render into, the scales, etc. From this you can render() a SVG group containing whatever you want.
