### ISSUE TITLE
Increasing the Label fontSize of y-axis

### ISSUE THREAD

**Issue by aruldd** [esnet/react-timeseries-charts#427]
I want to increase the font-size fo the Y-axis label, 

I have tried this :

```jsx
<YAxis
  id="cop"
  label="CoP"
  min={0}
  max={15}
  width="50"
  type="linear"
  style={{
    label: {
      stroke: '1px',
      fill: 'blue', // Default label color
      fontWeight: 100,
      fontSize: 24,
      font: '"Goudy Bookletter 1911", sans-serif"',
    },
  }}
/>
```

But this changes only the colour of the legend. I am unable to see any of the other parameters passed to the text in the SVG.

Thank you for the help!

**Comment by darkopetrovic** [comment]
Using a CSS style seems working: 

```
.yaxislabel {
  font-size: 14pt;
  font-family: Verdana, Geneva, Tahoma, sans-serif;
}
```

**Comment by Iman-Jamali** [comment]
I have the same issue. CSS style worked though.

**Comment by aruldd** [comment]
Thank you, the CSS styling worked.

**Comment by Oddisey** [comment]
For anyone else who come's across this issue, you can solve it by using "font-size" instead of fontSize and "font-family" instead of font. Like so:
`label: {
            stroke: "#0d18b7",
            fontWeight: 100,
            "font-size": 20,
            "font-family": "Roboto"
        }`
