### ISSUE TITLE
Errors when attempting to use Y-Axis type other than "linear"

### ISSUE THREAD

**Issue by apertome** [esnet/react-timeseries-charts#43]
I've been trying to create a LineChart with Y-Axis "log" scale type. I am charting owamp latency data, which often has a broad range of values (and loss, which I'll be plotting soon, even moreso). 

However, I'm getting errors such as:
createNodesFromMarkup.js:61 Error: Invalid value for <path> attribute d="M 1058.942027 NaN L 1057.469805 NaN L 1055.997582 NaN L 1054.52536 NaN L 1053.053138 NaN L 1051.580916 NaN L 1050.108693 NaN L 1048.636471 NaN L 1047.164249 NaN L 1045.692027 NaN L 1044.219805 NaN L 1042.747582 NaN L 1041.27536 NaN L 1039.803138 NaN L 1038.330916 NaN L 1036.858693 NaN L 1035.386471 NaN L 1033.914249 NaN L 1032.442027 NaN L 1030.969805 NaN L 1029.497582 NaN L 1028.02536 NaN L 1026.553138 NaN L 1025.080916 NaN L 1023.608693 NaN L 1
...

Trace:

createNodesFromMarkup	@	createNodesFromMarkup.js:61
dangerouslyRenderMarkup	@	Danger.js:89
processUpdates	@	DOMChildrenOperations.js:89
dangerouslyProcessChildrenUpdates	@	ReactDOMIDOperations.js:85
ReactDOMIDOperations_dangerouslyProcessChildrenUpdates	@	ReactPerf.js:66
processQueue	@	ReactMultiChild.js:160
updateChildren	@	ReactMultiChild.js:334
_updateDOMChildren	@	ReactDOMComponent.js:871
updateComponent	@	ReactDOMComponent.js:700
receiveComponent	@	ReactDOMComponent.js:645
receiveComponent	@	ReactReconciler.js:87
_updateRenderedComponent	@	ReactCompositeComponent.js:562
_performComponentUpdate	@	ReactCompositeComponent.js:544
updateComponent	@	ReactCompositeComponent.js:473
ReactCompositeComponent_updateComponent	@	ReactPerf.js:66
performUpdateIfNecessary	@	ReactCompositeComponent.js:421
performUpdateIfNecessary	@	ReactReconciler.js:102
runBatchedUpdates	@	ReactUpdates.js:129
perform	@	Transaction.js:136
perform	@	Transaction.js:136
perform	@	ReactUpdates.js:86
flushBatchedUpdates	@	ReactUpdates.js:147
ReactUpdates_flushBatchedUpdates	@	ReactPerf.js:66
closeAll	@	Transaction.js:202
perform	@	Transaction.js:149
batchedUpdates	@	ReactDefaultBatchingStrategy.js:62
enqueueUpdate	@	ReactUpdates.js:176
enqueueUpdate	@	ReactUpdateQueue.js:24
enqueueForceUpdate	@	ReactUpdateQueue.js:143
ReactComponent.forceUpdate	@	ReactComponent.js:86
(anonymous function)	@	chart1.jsx:225
l	@	jquery.min.js:4
c.fireWith	@	jquery.min.js:4
k	@	jquery.min.js:6
(anonymous function)	@	jquery.min.js:6

Peter suggested trying "Log" rather than "log," but that didn't work, either (though I got a different error). FWIW, I'm attempting to set the Log type when I create the charts, not change it on the fly.

**Comment by pjm17971** [comment]
I tried this out and it seems to work. At least for log and linear. Exp is broken apparently, it should be pow in the propTypes. I'll fix that. Anyway, here it is working:

<img width="615" alt="screen shot 2016-04-19 at 1 59 37 pm" src="https://cloud.githubusercontent.com/assets/1288813/14655432/2c0deaa2-0637-11e6-9ac2-de9518b98e9f.png">

```
<YAxis id="yaxis" label="label" min={1} max={1000} type="log" format=".2f" />
```

A couple of thoughts:
Firstly, a log scale that includes or crosses zero in the domain won't work. Getting NaNs in the y direction of the SVG would tend to indicate this, but it's hard to tell without tracking the data all the way though the code.
Secondly, I've only tested the v0.9 branch. You could try npm installing directly from github v0.9 branch and see if that works. I'm pretty sure we use the previous v0.8 code in the portal, with log scales, though.
