### ISSUE TITLE
Brushing selection control

### ISSUE THREAD

**Issue by pjm17971** [esnet/react-timeseries-charts#47]
Request to add additional functionality to the Brush control from @apertome:

 - Ability to have it load with no initial selection. Need way of specifying an empty range.
 - Have the selection cleared when the user clicks outside of the selected area along with programatic selection clearing

Most likely this would mean adapting the existing code to accept null as a TimeRange and providing a callback (if an existing one is not appropriate) to clear that state.

Additional comment:

> These could be added easily enough, but I thought I'd check with you guys to see if these would be desirable options from your point of view, before I go adding too much to the chart library itself. At the very least I think it needs to have a "clearBrush" function or something that can be called from other components. It might be nice to take it one step further and offer options for these behaviors, which I imagine might be fairly common.

@apertome If I've misrepresented this request, please make a note and I'll edit the description

**Comment by apertome** [comment]
No, it looks like you understood correctly. Thanks!
