### ISSUE TITLE
Building with Brunch

### ISSUE THREAD

**Issue by matthjes** [esnet/react-timeseries-charts#51]
Hi,
I'm fairly new to Javascript/React/Brunch etc. and I wanted to try out the time series charts. However, when I build the app using Brunch, the CSS gets compiled into a vendor.css, which is included in my index.html. But when I load the app I get an error message:
"Cannot find module: 'react-timeseries-charts/lib/baseline.css' from 'react-timeseries-charts/lib/baseline.js'"
baseline.js has a require("./baseline.css") statement, but all CSS is contained in the vendor.css.

Has anyone tried using the time series charts with Brunch?

**Comment by pjm17971** [comment]
I had to google what Brunch is. Cool. Anyway, with webpack you have to use the css loader. So maybe there's an equivalent on the brunch side? Maybe:
https://github.com/brunch/css-brunch
?

**Comment by matthjes** [comment]
​Hi,
I'm already using css-brunch.
But I think I'll try webpack, I'm still looking for a workflow that I like.
Btw: is it possible to create a dynamic time series​ chart where I
consantly add new data?

**Comment by pjm17971** [comment]
In the React world, just modify the timeseries you are passing into the chart and have it re-render.

Think in terms of what is my state, how does it change, and how do I render it? Your series is your state. You modify it by loading new data. And you render it by passing it to the chart.

For our applications we poll our server for the new data every 30 sec for the new timerange (say last day) and get back a new timeseries for that period, or we request blocks and merge them together. It's kind of up to you. But the series can change (each re-render if necessary).

In the 0.9 branch, which will soon be merged in and released, there's an example of realtime data.

**Comment by matthjes** [comment]
Thanks for the suggestions. I've tried webpack and it's working now.

Is there a way to make the height and width of a chart dependent on the size of the parent (div)?

**Comment by rweller59** [comment]
Could you provide some input on how you configured webpack to work with the chart library. I've been going around in circles without luck - all I get is the x-axis rendered.
