### ISSUE TITLE
Dynamic width and height

### ISSUE THREAD

**Issue by matthjes** [esnet/react-timeseries-charts#53]
Currently it seems like the width and height of a chart have to be set to fixed values (e.g. height property of ChartRow, width property of ChartContainer). Is there some way to make a chart responsive? There already is a closed issue (Feature/variable width layouts #13), but it only considers width and not height.

**Comment by pjm17971** [comment]
To control the chart's width, use the `<Resizable>` component, which is part of the charts library, to surround your `<ChartContainer>`. It will inject the width from the surrounding div into the top level of the chart. Heights are determined by the ChartRow heights, and are fixed. But this being react, you could use the same strategy as the [resizable](https://github.com/esnet/react-timeseries-charts/blob/master/src/resizable.jsx) code (which is pretty simple), to dynamically control the height you give to your `ChartRow`(s), taking into account the Timeline part at the bottom (which is fixed sized).
