### ISSUE TITLE
Unify styling across API

### ISSUE THREAD

**Issue by pjm17971** [esnet/react-timeseries-charts#57]
The aim of this item is to unify the styling of the charts and other components across the API. Particular chart styles have special requirements, for instance a scatter chart might want to style per-element, while this doesn't make sense for a line chart.

TODO:
 - [x] Scatter charts
 - [x] Area charts
 - [x] Line charts
 - [x] Bar charts
 - [x] Legends
 - [x] Baselines
 - [ ] Markers
 - [x] Docs page for styling based on this issue

In general we should follow these guidelines:

1) Where possible, **chart entities** can be in four states:
  - **normal**
  - **highlighted** - most likely if they are hovered over, but maybe because something in the rest of the page UI refers to that item (hovering over a table of values, for instance)
  - **selected** - most likely because it was clicked, but it might be selected elsewhere in the UI like the highlight
  - **muted**

2) A chart will take a single `TimeSeries`, but be able to specify multiple columns of the series. The series is passed in with the `series` prop and is a Pond `TimeSeries` object. The columns are passed in with the `columns` prop, and is an array of strings (the column names).

3) A chart takes a `style` prop, which may be a **style object** (see 4 below) or a **style function**.

4) The style object is a mapping from a column name to the style for that column. Each style object should specify each state (see 1 above) mapped to the **CSS specification** for that column, in that state. For example:
```
const scatterStyles = {
    gust: {
        normal: {
            fill: "red",
            opacity: 0.5
        }
    }
};
```
Maps the column named "gust" to one state ("normal"). For that state, the entity will be filled red, with opacity 0.5. In addition to normal we could also add other states (which should be optional and default to normal): highlighted, selected and muted.

5) The style function will be called with either each column, or each event/column, depending on the chart itself. i.e. a line chart and area chart will call the function with the column only. A scatter chart and bar chart would call the function for each event and column. For example:
```
style={(event, column) => ({
    normal: {
        fill: column === "station1" ? "green" : "orange",
        opacity: 0.7
    },
    highlighted: {
        fill: column === "station1" ? "green" : "orange",
        stroke: column === "station1" ? "#2db3d1" : "#2db3d1",
        opacity: 1.0
    },
    selected: {
        fill: "#2db3d1",
        stroke: "#2db3d1",
        strokeWidth: 3,
        opacity: 1.0
    }
})}
```

6) Some parts of the API have additional styles, for example legends, baselines etc. If possible these should use a subset of the above convention. If multiple styles are needed, you should use separate properties for those. For example "swatchStyle" and "labelStyle" for the legend's swatch and label. Then each of these should follow the above convention, if possible.

7) Sensible defaults should be provided so that the charts work without needing to specify a style. This should be clearly defined in each component as `defaultStyle`. The base style for this should be:
```
const defaultStyle = {
    normal: {fill: "steelblue", opacity: 0.8},
    highlighted: {fill: "#5a98cb", opacity: 1.0},
    selected: {fill: "orange", opacity: 1.0},
    muted: {fill: "steelblue", opacity: 0.4},
    text: {fill: "#333", stroke: "none"}
};
```

8) The main description of each component should have a header called Styling and provide a high level description of how to customize the styling of the component. More detailed information can be added to the props docs which are built to the API docs.

**Comment by jdugan1024** [comment]
Overall it looks good.

Two additional thoughts:

Sensible default styles should be set for all states.  Since we need to merge the passed in props with the defaults it doesn't really work to use the `getDefaultProps()` lifecycle method to hold the defaults.  I think I'd suggest just having an object called `defaultStyles` or something near the top of each component's file.

I'm not sure I understand the practical difference between selected and highlighted. They seem very similar to me. Is there a need for them to be separate?  (The answer may well be yes, I just can't see the use case at the moment.)

**Comment by pjm17971** [comment]
Highlighted is usually a subtle increase in brightness of the element as the use hovers over it, mostly to indicate that it is responding. If there is a hint box associated with hovering over an element then this helps identify what the hint box refers to.

Selected is an actual state controlled by the surrounding page. We typically show selected in with a very specific color (on the portal it's the ESnet cyan color). In contrast the other items may be muted.

**Comment by pjm17971** [comment]
Ok, this pretty much completes the styling across the main parts of the api, and now supports a `styler` which greatly simplifies the setting of styles. We may need to follow up on this over time, but this is a big step forward for the library, so I'm closing this out for v0.10.
