### ISSUE TITLE
Branch v0.9: Can't find variable: renderLine

### ISSUE THREAD

**Issue by matthjes** [esnet/react-timeseries-charts#58]
Hi,
I just tried branch v0.9 which uses the newest version of pond, but I'm getting an error when I load the page:

ReferenceError: Can't find variable: renderLine

Everything builds with no errors.

**Comment by matthjes** [comment]
It think this is my fault: when I installed react-timeseries-charts via npm install, it also installed pond version 0.3.0 as a dependency. I had to use esnet/react-timeseries-charts in package.json to install the correct version with pond v0.5.2 as dependecy.

**Comment by pjm17971** [comment]
@matthjes: until 0.9 lands (hopefully this week), if you want to play around, I would use the master branch (v0.9 branch has now been merged into master and fixes will go there). I've left the 0.9 branch since I know some people are using it, but I will delete it soon.
