### ISSUE TITLE
Boxplot feature

### ISSUE THREAD

**Issue by spinus** [esnet/react-timeseries-charts#64]
Hi, are you considering adding boxplot to library by any chance?

**Comment by jdugan1024** [comment]
@spinus we don't have a current need for boxplots so it's not high on our priority list. However, we'd welcome a pull request for that feature.

**Comment by pjm17971** [comment]
I've thought about adding this in the past. It's certainly in scope for this library. I'd imagine it being styled after the horizontal barcharts, would use pond.js to do the math (https://github.com/esnet/pond/issues/25), and be basically implemented like the current bar charts.

**Comment by pjm17971** [comment]
This is going to have to wait until the next version.

**Comment by pjm17971** [comment]
Some progress on this:

<img width="1225" alt="screen shot 2016-10-03 at 8 33 05 pm" src="https://cloud.githubusercontent.com/assets/1288813/19061811/a018dd0e-89a8-11e6-8246-8d495f291ec8.png">

It works by letting you add a regular TimeSeries to a BoxChart along with specifying an aggregation. This contains both the window size and how you want to map the boxes and center line to the reducers. For example:

```
            <BoxChart
              axis="hraxis"
              series={hr}
              column="hr"
              style={style}
              aggregation={{
                size: "5m",
                reducers: {
                  outer: [percentile(5), percentile(95)],
                  inner: [percentile(25), percentile(75)],
                  center: median(),
                },
              }}
            />
```

**Comment by spinus** [comment]
@pjm17971 nice stuff, thank you!

**Comment by pjm17971** [comment]
This is in 0.11.

**Comment by mhanney** [comment]
Thank you! I just finished moving my web app to 0.10. Really cool to work with. Thank you Peter.
