### ISSUE TITLE
Warning: Main: `key` is not a prop. Trying to access it will result in `undefined`

### ISSUE THREAD

**Issue by viky293** [esnet/react-timeseries-charts#66]
I was just experimenting with the react-time-series charts, they look really nice.  Is there a way we can fix this warning issue.

warning.js:44Warning: ChartRow: `key` is not a prop. Trying to access it will result in `undefined` being returned. If you need to access the same value within the child component, you should pass it as a different prop.

Using  "react-dom": "^15.1.0",

**Comment by pjm17971** [comment]
The next version of the charts library will support React 15, and that message will go away. In fact I was just working on that. I don't have an exact time frame however because a couple of other things need to be included as well. Getting closer though.

**Comment by pjm17971** [comment]
Fixed in the v0.10 branch, so I'm closing this.
