### ISSUE TITLE
Support React 15

### ISSUE THREAD

**Issue by pjm17971** [esnet/react-timeseries-charts#67]
The charts library generally works with React 15, but spits out several warning messages. Also, I think for the examples to work we need to upgrade React Router. And, as usual, there's probably other issues with the upgrade.

The goal would be to make it work on React 0.14 as well.

**Comment by pjm17971** [comment]
The example website in v0.10 is now completely React 15 compatible, and it should still work on React 0.14. Closing this out. We can reopen specific issues if the arise, but I think we're good here.

**Comment by patryk0605** [comment]
Getting a  `UNMET PEER DEPENDENCY react@15.3.1`. Can you please update? Thanks!

**Comment by avindra** [comment]
@pjm17971: Please see #75 as a resolution for this issue.
