### ISSUE TITLE
Object doesn't support property or method 'fill'

### ISSUE THREAD

**Issue by maksis** [esnet/react-timeseries-charts#71]
Fill is not supported by all browser: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/fill

https://github.com/esnet/react-timeseries-charts/blob/master/src/areachart.jsx#L162

**Comment by pjm17971** [comment]
Thanks! I'll fix this for the next release.

**Comment by pjm17971** [comment]
A polyfill was added for this in v0.10, which should fix the issue.
