### ISSUE TITLE
Roll in react-axis

### ISSUE THREAD

**Issue by pjm17971** [esnet/react-timeseries-charts#74]
The current implementation of both the yaxis and timeaxis are build using d3-axis. This has resulted in numerous problems in this libraries (short) life. In response the proposal is to develop react-axis to have all the functionality we need and then integrate that instead. This would still use d3 for format and scale, but would build the SVG with React instead. This would remove the last such piece of code from this library.

**Comment by sartaj10** [comment]
This has been done. Should I close it? @pjm17971

**Comment by pjm17971** [comment]
sure
