### ISSUE TITLE
Bug when deselecting/selecting metrics

### ISSUE THREAD

**Issue by patryk0605** [esnet/react-timeseries-charts#77]
I'm currently facing an issue that exists within the [DDoS example](http://software.es.net/react-timeseries-charts/#/ddos) where if you deselect both **Requests** and **Connections**, and only select **Connections** again, the rendered chart is cut off like so: 

![image](https://cloud.githubusercontent.com/assets/7227636/18450590/aba2163e-7901-11e6-9303-59f143c039bf.png)

**Comment by pjm17971** [comment]
Thanks for reporting this. What version of the code are you using? I feel like I've seen this before, so I'd like to figure out if this got fixed.

**Comment by patryk0605** [comment]
`"react-timeseries-charts": "0.9.2"`, thanks!

**Comment by pjm17971** [comment]
A fix for this is now in v0.10.

**Comment by patryk0605** [comment]
Great! Thanks for the quick turnaround.
