### ISSUE TITLE
Hidden axis support

### ISSUE THREAD

**Issue by pjm17971** [esnet/react-timeseries-charts#78]
For @apertome:

> If there were a property to allow me to hide a YAxis, that would help in this situation, and it could also be more generally useful as well. I tried disabling an axis and got it greyed it out, but that didn't help. I thought about trying to turn the opacity all the way down, but it would still be taking up space (I also tried setting width to 0 but that didn't work, either, although there might be a way to force it). Ideally I'd like to have the axis present and be able to manipulate it like any other, just not have it display at all.

**Comment by pjm17971** [comment]
@apertome so I have a test for making this work, but I thought I'd run it by you. It didn't make the latest release, unfortunately. So the approach:

1) You don't need to specify an axis in a chart. However, if it needs a yScale, they will error on you because obviously it doesn't get one from the axis anymore. I've not really figured out exactly how to expose that error, propTypes fails me here because of the injection of the prop when there is an axis.
2) This allows you to use something like the EventChart, which doesn't depend on having a y-axis without having to specify one anyway, which was kind of lame.
3) If you have a LineChart of something that does require a y-scale, you can pass in a `yScale` prop yourself (a d3 scale), and you have no axis, but still have the scale of an axis.

e.g.

```
        const scale = scaleLinear()
            .domain([0.5, 1.5])
            .range([500, 0]);
```
...
```
                            <ChartContainer  timeRange={range}>
                                    <Charts>
                                        <LineChart
                                            yScale={scale}
                                            series={currencySeries}
                                            columns={["aud", "euro"]}
                                            style={style} />
                                        <Baseline
                                           yScale={scale}
                                            value={1.0}
                                            label="Baseline" />
                                    </Charts>
                                </ChartRow>
                            </ChartContainer>
```

Do you think this works for your use case?

**Comment by thetwosents** [comment]
Would love to see this added also. We need to hide the axis for one of our chart and currently cannot get it done. Is this a thing?

**Comment by pjm17971** [comment]
Yes, it's a thing. It will be part of the next release.

**Comment by ambethia** [comment]
@pjm17971 was this ever included in a release? I don't see it in the docs, or in the source for that matter. Just want to make sure I'm not overlooking it.

**Comment by pjm17971** [comment]
Yes, you can omit an axis in the current released code:
https://github.com/esnet/react-timeseries-charts/blob/master/CHANGES.md#v0120

The outage events example uses this:
http://software.es.net/react-timeseries-charts/#/example/outages

Basically, if it's a chart that doesn't need a y-axis (say if you are overlaying errors as lines on top of another chart and they have no y dimension), then so long as that code doesn't mind there being no y-scale, it will render fine (the container and row code no longer enforces this, which is what this issue was addressing). Also, in general, charts are just getting their y-axis injected into them as a yscale prop, so if you provide this (d3.scale) you can omit an axis. You just have to supply the scale yourself.

It probably would be nice to just have a `hidden` prop on the an axis, but this fit in better with the existing code and we moved on.

Let me know if you have any trouble.

**Comment by ambethia** [comment]
Ok, that's perfect. Thanks for pointing me to the example too. I was just looking on `YAxis` for something like `hidden`.

For anyone looking for quick answer, I did something like this on `LineChart`:

```
yScale={scaleLinear().domain([series.min('priceBTC'), series.max('priceBTC')]).range([height - AXIS_MARGIN, AXIS_MARGIN]).nice()}
```

`AXIS_MARGIN` is a const in `ChartRow` (`5`) that I just copied to my component.
