### ISSUE TITLE
Issues with AreaChart (0.10.0)

### ISSUE THREAD

**Issue by maksis** [esnet/react-timeseries-charts#79]
AreaChart doesn't work when no style prop is provided with version 0.10.0.

`TypeError: Cannot read property 'normal' of null(…)   AreaChart.js:248`

**Comment by pjm17971** [comment]
Thanks for reporting this. v0.10.1contains the fix. You should probably pass a style in though, unless you love "steelblue".

**Comment by maksis** [comment]
Ah right, I have a simple chart that is almost identical to your [AreaChart example](http://software.es.net/react-timeseries-charts/#/api/AreaChart?_k=v9dl17) and I obviously need to pass in a style to get different colors for up/down after the upgrade.

ps. LineChart is being used in the style section on that doc page and the formatting is broken
