### ISSUE TITLE
Source code request for my.es.net implementation 

### ISSUE THREAD

**Issue by patryk0605** [esnet/react-timeseries-charts#82]
Would you be able to provide the source code for the **Total Traffic** implementation on this page: [https://my.es.net/site/ames/#flow/](https://my.es.net/site/ames/#flow/)?

Or should I contact tools@es.net? Not sure if you're part of the same team. If not, sorry for the confusion :)

**Comment by pjm17971** [comment]
What's running on that page is an older implementation that was coded specifically for that page and doesn't use React. That page will be replaced in the coming week as we roll the open source libraries back in across the whole of the ESnet Portal. The new flow page follows the implementation in the traffic breakdown example: http://software.es.net/react-timeseries-charts/#/example/interfaces. I'm hoping to open source the front end of the Portal as well, but that depends on multiple factors, some of which aren't in our control.

**Comment by pjm17971** [comment]
I should also mention that in the next version of the charts library, I was planning on moving out the horizontal barcharts code to new library. I'm interested in building up more of a library built on top of the charts library that is concerned with doing breakdowns and comparing multiple timeseries against each other. At that point I think a channel style view would fit in. BTW, also see the cycing example for displaying multiple channels of data together.

To generate a view similar to the one on the current flow page, you can just stack multiple charts on top of each other. It's possible to use Pond to do the summing, if what you have is n timeseries and you want to see the sum and the breakdown. To sync them to each other the tracker time and current timerange is state on the page component. On top of that you can control the timerange with the controls on the side etc which just set this.state.timerange and all the charts re-render with that. We set a timer on componentDidMount to go off every 30 sec, get the new current timerange and fetch updated data. There's the complication of this having persistent URLs. I can go into how it works on the new flow page if that part is the sticking point? 

Perhaps send me an email? pmurphy@es.net.

**Comment by patryk0605** [comment]
Thanks for the great amount of detail! I really appreciate it. 

Is it possible with the current react version to show the number on the tracker line like in the implementation? For example, hovering over **9am** shows **41.8M** for data above x-axis and **432M** for data below x-axis. I browsed through the api docs and examples, and did not see an example of this being used. Here is a reference image: 

![image](https://cloud.githubusercontent.com/assets/7227636/18676842/f816c3ec-7f24-11e6-98bf-2d69fe35f5f8.png)

I have the main parts of the chart working on my end, just trying to get the aesthetics and minor extra details to work as desired :)

**Comment by pjm17971** [comment]
No, sorry. Feel free to add an Issue for this. The current tracker can only show a flag style tracker at the top. The reason for the change was better consistency across all the chart types.

**Comment by patryk0605** [comment]
Created #83, thanks!
