### ISSUE TITLE
Option to show old-style tracker for up/down charts

### ISSUE THREAD

**Issue by patryk0605** [esnet/react-timeseries-charts#83]
Using the following image as reference: 

![image](https://cloud.githubusercontent.com/assets/7227636/18681663/103ce3f4-7f37-11e6-9e95-f06d44cf00c5.png)

Would it be possible for the tracker to show the current value the tracker line is hovering over? For example, hovering over **9am** shows **41.8M** for data above x-axis and **432M** for data below x-axis.

**Comment by sartaj10** [comment]
You can do this now

![screen shot 2018-05-08 at 5 23 48 pm](https://user-images.githubusercontent.com/5708022/39789630-ebddc09e-52e5-11e8-913d-16e00c687743.png)
