### ISSUE TITLE
Resizable inconsistent sizing

### ISSUE THREAD

**Issue by pdf** [esnet/react-timeseries-charts#85]
`Resizable` seems to generate inconsistent sizing, sometimes shrinking far to much, and sometimes expanding beyond the container element.  This may have something to do with the styling of the wrapping element, however the current approach does not seem optimal.

Instead of relying on the rendered DOM to obtain sizing information, I'd like to propose changing the SVG to use a `viewBox`, which allows layout and sizing inside the SVG using a fixed width/height, decoupled from the display size.  Adopting `viewBox` would make it possible to adjust the displayed size using whatever means the user sees fit, including `width: 100%;`, FlexBox, or whatever, and not have to rely on resize events, DOM inspection or refs.

**Comment by pjm17971** [comment]
I'm going to close this because I don't think this is realistic at this point.
