### ISSUE TITLE
Custom timeFormat on the time axis

### ISSUE THREAD

**Issue by pdf** [esnet/react-timeseries-charts#86]
It looks like the `format` prop that's passed down to the `TimeAxis` only supports a few predefined values.  I'd like to retain the multi-scale formatting that's used by default, but with 24hr time (why they chose zero-padded 12hr time by default in `d3-scale` escapes me).  If I could pass a func per the [d3-time-format docs](https://github.com/d3/d3-time-format/blob/master/README.md#d3-time-format), I think that would work?

**Comment by pjm17971** [comment]
Seems reasonable. I'll try to make that change for the next release.
