### ISSUE TITLE
LineChart style mismatch doc and code

### ISSUE THREAD

**Issue by jverhoeven** [esnet/react-timeseries-charts#93]
There seems a discrepancy between the code and the API docs when it comes to the style property of LineChart:

Code says that a 'normal' key is required:

`style = merge(true, defaultStyle.normal, styleMap.normal);`

where the LineChart API doc does not show a 'normal' key at all:

const lineStyles = {
     value: {
         stroke: "steelblue",
         strokeWidth: 1,
         strokeDasharray: "4,2"
     }
 };

 <LineChart style={lineStyles} ... />

Adding the 'normal' property makes it work.

Not sure what is right (doc or code), however the Baselines demo also seems to omit the 'normal' key (and as a result does not pick up another style as well).

**Comment by pjm17971** [comment]
Thanks for the report. Oops, old docs, new code. I've made this change in my branch and so I'll push the website update with the next version. In the mean time, yes, it should be an object with normal in it. See the example for area chart, though without the top level of area and line. It's probably better to use the styler, if possible.
